import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from "react";

export type Language = "en" | "bn" | "ar" | "hi" | "es" | "fr" | "de" | "zh" | "ja" | "ko";

interface Translations {
  [key: string]: string;
}

// Short language codes for compact display
const languageFlags: Record<Language, string> = {
  en: "EN", bn: "বা", ar: "عر", hi: "हि", es: "ES", fr: "FR", de: "DE", zh: "中", ja: "日", ko: "한",
};

// Shared page keys that all non-EN languages need
const sharedPageKeys = {
  // About
  "about.badge": "", "about.title": "", "about.title_highlight": "", "about.subtitle": "",
  "about.mission_badge": "", "about.mission_title": "", "about.mission_desc": "",
  "about.mission_1": "", "about.mission_2": "", "about.mission_3": "", "about.mission_4": "",
  "about.values_badge": "", "about.values_title": "",
  "about.value_innovation": "", "about.value_innovation_desc": "",
  "about.value_client": "", "about.value_client_desc": "",
  "about.value_excellence": "", "about.value_excellence_desc": "",
  "about.value_integrity": "", "about.value_integrity_desc": "",
  "about.team_badge": "", "about.team_title": "",
  "about.cta_title": "", "about.cta_desc": "", "about.cta_button": "", "about.cta_services": "",
  "about.stat_projects": "", "about.stat_clients": "", "about.stat_years": "", "about.stat_support": "",
  // Services page
  "services.page_badge": "", "services.page_title": "", "services.page_title_highlight": "", "services.page_subtitle": "",
  "services.free_consultation": "", "services.discuss_whatsapp": "", "services.learn_more": "",
  "services.cta_title": "", "services.cta_desc": "", "services.cta_start": "", "services.cta_view_work": "",
  // Services features
  "services.feat_hrm": "", "services.feat_hrm_desc": "",
  "services.feat_crm": "", "services.feat_crm_desc": "",
  "services.feat_erp": "", "services.feat_erp_desc": "",
  "services.feat_web": "", "services.feat_web_desc": "",
  "services.feat_mobile": "", "services.feat_mobile_desc": "",
  "services.feat_api": "", "services.feat_api_desc": "",
  "services.feat_payment": "", "services.feat_payment_desc": "",
  "services.feat_banking": "", "services.feat_banking_desc": "",
  "services.feat_compliance": "", "services.feat_compliance_desc": "",
  "services.feat_ml": "", "services.feat_ml_desc": "",
  "services.feat_analytics": "", "services.feat_analytics_desc": "",
  "services.feat_chatbot": "", "services.feat_chatbot_desc": "",
  // Blog
  "blog.badge": "", "blog.title": "", "blog.title_highlight": "", "blog.subtitle": "",
  "blog.loading": "", "blog.no_posts": "", "blog.read_more": "", "blog.contact_us": "",
  "blog.stay_updated": "", "blog.stay_updated_desc": "", "blog.subscribe": "",
  // Portfolio
  "portfolio.badge": "", "portfolio.title": "", "portfolio.title_highlight": "", "portfolio.subtitle": "",
  "portfolio.loading": "", "portfolio.coming_soon": "", "portfolio.discuss_project": "",
  "portfolio.preview": "", "portfolio.view_case_study": "", "portfolio.get_quote": "",
  "portfolio.cta_title": "", "portfolio.cta_desc": "", "portfolio.cta_start": "",
  // Demo
  "demo.badge": "", "demo.title": "", "demo.title_highlight": "", "demo.subtitle": "",
  "demo.search_placeholder": "", "demo.all": "", "demo.featured": "",
  "demo.no_demos": "", "demo.loading": "",
  "demo.view_demo": "", "demo.quote": "", "demo.views": "",
  "demo.no_match": "", "demo.no_match_desc": "", "demo.clear_search": "", "demo.request_demo": "",
  "demo.custom_title": "", "demo.custom_desc": "", "demo.schedule": "", "demo.chat_whatsapp": "",
  // Privacy / Terms
  "privacy.title": "", "privacy.back": "", "terms.title": "", "terms.back": "",
};

const translationsMap: Record<Language, Translations> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.demo": "Demo",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "cta.get_started": "Get Started",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.made_with": "Made with",
    "footer.enterprise_solutions": "Enterprise Solutions",
    "footer.custom_development": "Custom Development",
    "footer.security_finance": "Security & Finance",
    "footer.ai_integration": "AI Integration",
    "footer.about_us": "About Us",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    // Hero
    "hero.badge": "Innovating Tomorrow, Today",
    "hero.title1": "Transform Your",
    "hero.title2": "Business",
    "hero.title2_suffix": "with",
    "hero.title3": "Cutting-Edge Tech",
    "hero.subtitle": "We deliver innovative software solutions, AI-powered systems, and expert IT consulting to help businesses thrive in the digital age.",
    "hero.cta_project": "Start Your Project",
    "hero.cta_demo": "View Live Demos",
    "hero.stat_projects": "Projects Delivered",
    "hero.stat_satisfaction": "Client Satisfaction",
    "hero.stat_experts": "Team Experts",
    "hero.scroll": "Scroll",
    "hero.tag_software": "Software Development",
    "hero.tag_ai": "AI Solutions",
    "hero.tag_consulting": "IT Consulting",
    "hero.tag_cloud": "Cloud Services",
    // Services
    "services.badge": "Our Services",
    "services.title": "What We",
    "services.title_highlight": "Offer",
    "services.subtitle": "Comprehensive technology solutions designed to accelerate your business growth and digital transformation.",
    "services.chat_now": "Chat Now",
    "services.view_all": "View All Services",
    "services.enterprise": "Enterprise Solutions",
    "services.enterprise_desc": "Comprehensive business management systems tailored for your organization.",
    "services.custom": "Custom Development",
    "services.custom_desc": "Bespoke software solutions built to match your unique business requirements.",
    "services.security": "Security & Finance",
    "services.security_desc": "Secure financial systems and compliance-ready security solutions.",
    "services.ai": "AI Integration",
    "services.ai_desc": "Leverage artificial intelligence to automate and optimize your business.",
    // Services features
    "services.feat_hrm": "HRM System",
    "services.feat_hrm_desc": "Complete human resource management with payroll, attendance, leave management, and performance tracking.",
    "services.feat_crm": "CRM System",
    "services.feat_crm_desc": "Customer relationship management to boost sales, track leads, and improve customer retention.",
    "services.feat_erp": "ERP System",
    "services.feat_erp_desc": "Enterprise resource planning for seamless business operations across all departments.",
    "services.feat_web": "Web Applications",
    "services.feat_web_desc": "Modern, responsive web applications using React, Next.js, and other cutting-edge technologies.",
    "services.feat_mobile": "Mobile Apps",
    "services.feat_mobile_desc": "Native and cross-platform mobile applications for iOS and Android platforms.",
    "services.feat_api": "API Development",
    "services.feat_api_desc": "Robust RESTful and GraphQL APIs for seamless integration with existing systems.",
    "services.feat_payment": "Payment Systems",
    "services.feat_payment_desc": "Secure payment gateways, transaction processing, and financial management tools.",
    "services.feat_banking": "Banking Solutions",
    "services.feat_banking_desc": "Core banking systems, mobile banking apps, and financial reporting platforms.",
    "services.feat_compliance": "Compliance Tools",
    "services.feat_compliance_desc": "Regulatory compliance management and audit trail systems for various industries.",
    "services.feat_ml": "Machine Learning",
    "services.feat_ml_desc": "Custom ML models for predictive analytics, recommendation systems, and automation.",
    "services.feat_analytics": "Data Analytics",
    "services.feat_analytics_desc": "AI-powered business intelligence, data visualization, and reporting dashboards.",
    "services.feat_chatbot": "Chatbots & NLP",
    "services.feat_chatbot_desc": "Intelligent chatbots, voice assistants, and natural language processing solutions.",
    // Contact
    "contact.badge": "Get in Touch",
    "contact.title": "Let's Build",
    "contact.title_highlight": "Something Great",
    "contact.subtitle": "Ready to transform your business with cutting-edge technology? Get in touch and let's discuss your project.",
    "contact.email_us": "Email Us",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Location",
    "contact.form_title": "Send us a message",
    "contact.form_subtitle": "We'll respond within 24 hours",
    "contact.name": "Your Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.subject": "Subject",
    "contact.message": "Your Message",
    "contact.message_placeholder": "Tell us about your project...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.success_title": "Message sent!",
    "contact.success_desc": "We'll get back to you as soon as possible.",
    "contact.error": "Failed to send message. Please try again.",
    "contact.characters": "characters",
    "contact.page_badge": "Contact Us",
    "contact.page_title": "Let's Start a",
    "contact.page_title_highlight": "Conversation",
    "contact.page_subtitle": "Have a project in mind? We'd love to hear from you. Get in touch and let's create something amazing together.",
    "contact.visit_us": "Visit Us",
    "contact.business_hours": "Business Hours",
    "contact.hours_value": "Sun - Thu: 9AM - 6PM",
    "contact.call_us": "Call Us",
    // About
    "about.badge": "About Us",
    "about.title": "Building the Future of",
    "about.title_highlight": "Technology",
    "about.subtitle": "engineersTech is a leading software development company based in Bangladesh, dedicated to delivering innovative enterprise solutions that transform businesses.",
    "about.mission_badge": "Our Mission",
    "about.mission_title": "Empowering Businesses Through Technology",
    "about.mission_desc": "At engineersTech, we believe in the transformative power of technology. Our mission is to help businesses of all sizes leverage cutting-edge solutions to streamline operations, enhance productivity, and achieve sustainable growth.",
    "about.mission_1": "Custom software tailored to your unique needs",
    "about.mission_2": "Scalable solutions that grow with your business",
    "about.mission_3": "24/7 dedicated support and maintenance",
    "about.mission_4": "Agile development methodology for faster delivery",
    "about.values_badge": "Our Values",
    "about.values_title": "What Drives Us",
    "about.value_innovation": "Innovation First",
    "about.value_innovation_desc": "We constantly push the boundaries of technology to deliver cutting-edge solutions.",
    "about.value_client": "Client-Centric",
    "about.value_client_desc": "Your success is our priority. We work closely with you to understand and meet your needs.",
    "about.value_excellence": "Excellence",
    "about.value_excellence_desc": "We maintain the highest standards of quality in every project we undertake.",
    "about.value_integrity": "Integrity",
    "about.value_integrity_desc": "Transparency and honesty form the foundation of our business relationships.",
    "about.team_badge": "Our Team",
    "about.team_title": "Meet the Experts",
    "about.cta_title": "Ready to Work With Us?",
    "about.cta_desc": "Let's discuss how we can help transform your business with our technology solutions.",
    "about.cta_button": "Get in Touch",
    "about.cta_services": "Our Services",
    "about.stat_projects": "Projects Completed",
    "about.stat_clients": "Happy Clients",
    "about.stat_years": "Years Experience",
    "about.stat_support": "Support Available",
    // Services page
    "services.page_badge": "Our Services",
    "services.page_title": "Enterprise Solutions for",
    "services.page_title_highlight": "Modern Business",
    "services.page_subtitle": "From custom software development to AI integration, we provide comprehensive technology solutions that drive growth and efficiency.",
    "services.free_consultation": "Get a Free Consultation",
    "services.discuss_whatsapp": "Discuss on WhatsApp",
    "services.learn_more": "Learn More",
    "services.cta_title": "Ready to Transform Your Business?",
    "services.cta_desc": "Let's discuss how our solutions can help you achieve your goals.",
    "services.cta_start": "Start Your Project",
    "services.cta_view_work": "View Our Work",
    // Blog
    "blog.badge": "Our Blog",
    "blog.title": "Insights &",
    "blog.title_highlight": "Updates",
    "blog.subtitle": "Stay updated with the latest trends in technology, software development, and digital transformation.",
    "blog.loading": "Loading posts...",
    "blog.no_posts": "No blog posts published yet. Check back soon for updates!",
    "blog.read_more": "Read More",
    "blog.contact_us": "Contact Us",
    "blog.stay_updated": "Stay Updated",
    "blog.stay_updated_desc": "Want to receive updates about new posts and tech insights? Get in touch with us.",
    "blog.subscribe": "Subscribe to Updates",
    // Portfolio
    "portfolio.badge": "Our Portfolio",
    "portfolio.title": "Case Studies &",
    "portfolio.title_highlight": "Success Stories",
    "portfolio.subtitle": "Explore our completed projects and see how we've helped businesses transform through innovative technology solutions.",
    "portfolio.loading": "Loading projects...",
    "portfolio.coming_soon": "Portfolio coming soon! We're documenting our amazing projects.",
    "portfolio.discuss_project": "Discuss Your Project",
    "portfolio.preview": "Preview",
    "portfolio.view_case_study": "View Case Study",
    "portfolio.get_quote": "Get Quote",
    "portfolio.cta_title": "Have a Project in Mind?",
    "portfolio.cta_desc": "Let's discuss how we can help bring your vision to life with our expertise.",
    "portfolio.cta_start": "Start Your Project",
    // Demo
    "demo.badge": "Project Showcase",
    "demo.title": "Explore Our",
    "demo.title_highlight": "Project Showcase",
    "demo.subtitle": "Discover our portfolio of successful projects. Interactive demos, live previews, and detailed case studies.",
    "demo.search_placeholder": "Search projects by name or description...",
    "demo.all": "All Projects",
    "demo.featured": "Featured",
    "demo.no_demos": "Projects Coming Soon",
    "demo.loading": "Loading projects...",
    "demo.view_demo": "View Demo",
    "demo.quote": "Quote",
    "demo.views": "views",
    "demo.no_match": "No Matching Projects",
    "demo.no_match_desc": "Try adjusting your search or browse all projects.",
    "demo.clear_search": "Clear Search",
    "demo.request_demo": "Request a Demo",
    "demo.custom_title": "Want a Custom Solution?",
    "demo.custom_desc": "Schedule a personalized consultation tailored to your specific requirements.",
    "demo.schedule": "Schedule Consultation",
    "demo.chat_whatsapp": "Chat on WhatsApp",
    // Privacy / Terms
    "privacy.title": "Privacy Policy",
    "privacy.back": "Back to Home",
    "terms.title": "Terms of Service",
    "terms.back": "Back to Home",
  },
  bn: {
    "nav.home": "হোম", "nav.about": "আমাদের সম্পর্কে", "nav.services": "সেবাসমূহ", "nav.portfolio": "পোর্টফোলিও", "nav.demo": "ডেমো", "nav.blog": "ব্লগ", "nav.contact": "যোগাযোগ",
    "cta.get_started": "শুরু করুন",
    "footer.services": "সেবাসমূহ", "footer.company": "কোম্পানি", "footer.contact": "যোগাযোগ", "footer.rights": "সর্বস্বত্ব সংরক্ষিত।", "footer.made_with": "তৈরি করা হয়েছে",
    "footer.enterprise_solutions": "এন্টারপ্রাইজ সমাধান", "footer.custom_development": "কাস্টম ডেভেলপমেন্ট", "footer.security_finance": "নিরাপত্তা ও অর্থায়ন", "footer.ai_integration": "এআই ইন্টিগ্রেশন",
    "footer.about_us": "আমাদের সম্পর্কে", "footer.privacy": "গোপনীয়তা নীতি", "footer.terms": "সেবার শর্তাবলী",
    "hero.badge": "আজই আগামীকালের উদ্ভাবন", "hero.title1": "আপনার ব্যবসাকে", "hero.title2": "রূপান্তর", "hero.title2_suffix": "করুন", "hero.title3": "অত্যাধুনিক প্রযুক্তিতে",
    "hero.subtitle": "আমরা উদ্ভাবনী সফটওয়্যার সমাধান, এআই-চালিত সিস্টেম এবং বিশেষজ্ঞ আইটি পরামর্শ প্রদান করি।",
    "hero.cta_project": "আপনার প্রকল্প শুরু করুন", "hero.cta_demo": "লাইভ ডেমো দেখুন",
    "hero.stat_projects": "প্রকল্প সম্পন্ন", "hero.stat_satisfaction": "ক্লায়েন্ট সন্তুষ্টি", "hero.stat_experts": "দলের বিশেষজ্ঞ",
    "hero.scroll": "স্ক্রল", "hero.tag_software": "সফটওয়্যার ডেভেলপমেন্ট", "hero.tag_ai": "এআই সমাধান", "hero.tag_consulting": "আইটি পরামর্শ", "hero.tag_cloud": "ক্লাউড সেবা",
    "services.badge": "আমাদের সেবাসমূহ", "services.title": "আমরা কি", "services.title_highlight": "অফার করি", "services.subtitle": "আপনার ব্যবসার বৃদ্ধি ত্বরান্বিত করতে ব্যাপক প্রযুক্তি সমাধান।",
    "services.chat_now": "চ্যাট করুন", "services.view_all": "সব সেবা দেখুন",
    "services.enterprise": "এন্টারপ্রাইজ সমাধান", "services.enterprise_desc": "আপনার প্রতিষ্ঠানের জন্য তৈরি ব্যাপক ব্যবসা ব্যবস্থাপনা সিস্টেম।",
    "services.custom": "কাস্টম ডেভেলপমেন্ট", "services.custom_desc": "আপনার অনন্য ব্যবসায়িক প্রয়োজনীয়তার সাথে মিলানো সফটওয়্যার সমাধান।",
    "services.security": "নিরাপত্তা ও অর্থায়ন", "services.security_desc": "নিরাপদ আর্থিক সিস্টেম এবং সম্মতি-প্রস্তুত নিরাপত্তা সমাধান।",
    "services.ai": "এআই ইন্টিগ্রেশন", "services.ai_desc": "আপনার ব্যবসা স্বয়ংক্রিয় ও অপ্টিমাইজ করতে কৃত্রিম বুদ্ধিমত্তা।",
    "contact.badge": "যোগাযোগ করুন", "contact.title": "আসুন তৈরি করি", "contact.title_highlight": "অসাধারণ কিছু",
    "contact.subtitle": "অত্যাধুনিক প্রযুক্তিতে আপনার ব্যবসা রূপান্তর করতে প্রস্তুত?",
    "contact.email_us": "ইমেইল করুন", "contact.whatsapp": "হোয়াটসঅ্যাপ", "contact.location": "অবস্থান",
    "contact.form_title": "আমাদের একটি বার্তা পাঠান", "contact.form_subtitle": "আমরা ২৪ ঘন্টার মধ্যে উত্তর দেব",
    "contact.name": "আপনার নাম", "contact.email": "ইমেইল ঠিকানা", "contact.phone": "ফোন নম্বর", "contact.subject": "বিষয়",
    "contact.message": "আপনার বার্তা", "contact.message_placeholder": "আপনার প্রকল্প সম্পর্কে বলুন...",
    "contact.send": "বার্তা পাঠান", "contact.sending": "পাঠানো হচ্ছে...",
    "contact.success_title": "বার্তা পাঠানো হয়েছে!", "contact.success_desc": "আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
    "contact.error": "বার্তা পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।", "contact.characters": "অক্ষর",
    "contact.page_badge": "যোগাযোগ", "contact.page_title": "আসুন শুরু করি একটি", "contact.page_title_highlight": "কথোপকথন",
    "contact.page_subtitle": "একটি প্রকল্প মনে আছে? আমরা আপনার কাছ থেকে শুনতে চাই।",
    "contact.visit_us": "আমাদের দেখুন", "contact.business_hours": "কর্ম সময়", "contact.hours_value": "রবি - বৃহঃ: সকাল ৯ - সন্ধ্যা ৬", "contact.call_us": "কল করুন",
    // About
    "about.badge": "আমাদের সম্পর্কে", "about.title": "প্রযুক্তির ভবিষ্যৎ", "about.title_highlight": "নির্মাণ", "about.subtitle": "engineersTech বাংলাদেশ ভিত্তিক একটি শীর্ষস্থানীয় সফটওয়্যার ডেভেলপমেন্ট কোম্পানি।",
    "about.mission_badge": "আমাদের মিশন", "about.mission_title": "প্রযুক্তির মাধ্যমে ব্যবসায়িক ক্ষমতায়ন",
    "about.mission_desc": "engineersTech-এ আমরা প্রযুক্তির রূপান্তরমূলক শক্তিতে বিশ্বাস করি।",
    "about.mission_1": "আপনার অনন্য চাহিদা অনুযায়ী কাস্টম সফটওয়্যার", "about.mission_2": "আপনার ব্যবসার সাথে বৃদ্ধি পায় এমন স্কেলেবল সমাধান",
    "about.mission_3": "২৪/৭ নিবেদিত সহায়তা ও রক্ষণাবেক্ষণ", "about.mission_4": "দ্রুত ডেলিভারির জন্য এজাইল ডেভেলপমেন্ট পদ্ধতি",
    "about.values_badge": "আমাদের মূল্যবোধ", "about.values_title": "আমাদের চালিকা শক্তি",
    "about.value_innovation": "উদ্ভাবন প্রথম", "about.value_innovation_desc": "আমরা ক্রমাগত প্রযুক্তির সীমানা ঠেলে দিই।",
    "about.value_client": "ক্লায়েন্ট-কেন্দ্রিক", "about.value_client_desc": "আপনার সাফল্য আমাদের অগ্রাধিকার।",
    "about.value_excellence": "শ্রেষ্ঠত্ব", "about.value_excellence_desc": "প্রতিটি প্রকল্পে সর্বোচ্চ মানের মান বজায় রাখি।",
    "about.value_integrity": "সততা", "about.value_integrity_desc": "স্বচ্ছতা এবং সততা আমাদের ব্যবসায়িক সম্পর্কের ভিত্তি।",
    "about.team_badge": "আমাদের টিম", "about.team_title": "বিশেষজ্ঞদের সাথে পরিচিত হন",
    "about.cta_title": "আমাদের সাথে কাজ করতে প্রস্তুত?", "about.cta_desc": "আমাদের প্রযুক্তি সমাধান দিয়ে আপনার ব্যবসা রূপান্তর করতে আলোচনা করি।",
    "about.cta_button": "যোগাযোগ করুন", "about.cta_services": "আমাদের সেবা",
    "about.stat_projects": "প্রকল্প সম্পন্ন", "about.stat_clients": "সুখী ক্লায়েন্ট", "about.stat_years": "বছরের অভিজ্ঞতা", "about.stat_support": "সার্বক্ষণিক সহায়তা",
    // Services page
    "services.page_badge": "আমাদের সেবাসমূহ", "services.page_title": "আধুনিক ব্যবসার জন্য", "services.page_title_highlight": "এন্টারপ্রাইজ সমাধান",
    "services.page_subtitle": "কাস্টম সফটওয়্যার ডেভেলপমেন্ট থেকে এআই ইন্টিগ্রেশন পর্যন্ত, আমরা ব্যাপক প্রযুক্তি সমাধান প্রদান করি।",
    "services.free_consultation": "বিনামূল্যে পরামর্শ নিন", "services.discuss_whatsapp": "হোয়াটসঅ্যাপে আলোচনা করুন", "services.learn_more": "আরও জানুন",
    "services.cta_title": "আপনার ব্যবসা রূপান্তর করতে প্রস্তুত?", "services.cta_desc": "আমাদের সমাধান আপনার লক্ষ্য অর্জনে কিভাবে সাহায্য করতে পারে তা আলোচনা করি।",
    "services.cta_start": "আপনার প্রকল্প শুরু করুন", "services.cta_view_work": "আমাদের কাজ দেখুন",
    // Services features
    "services.feat_hrm": "এইচআরএম সিস্টেম", "services.feat_hrm_desc": "বেতন, উপস্থিতি, ছুটি ব্যবস্থাপনা এবং কর্মক্ষমতা ট্র্যাকিং সহ সম্পূর্ণ মানব সম্পদ ব্যবস্থাপনা।",
    "services.feat_crm": "সিআরএম সিস্টেম", "services.feat_crm_desc": "বিক্রয় বাড়াতে, লিড ট্র্যাক করতে এবং গ্রাহক ধরে রাখতে গ্রাহক সম্পর্ক ব্যবস্থাপনা।",
    "services.feat_erp": "ইআরপি সিস্টেম", "services.feat_erp_desc": "সকল বিভাগে নিরবচ্ছিন্ন ব্যবসায়িক কার্যক্রমের জন্য এন্টারপ্রাইজ রিসোর্স প্ল্যানিং।",
    "services.feat_web": "ওয়েব অ্যাপ্লিকেশন", "services.feat_web_desc": "React, Next.js এবং অন্যান্য অত্যাধুনিক প্রযুক্তি ব্যবহার করে আধুনিক ওয়েব অ্যাপ্লিকেশন।",
    "services.feat_mobile": "মোবাইল অ্যাপ", "services.feat_mobile_desc": "iOS এবং Android প্ল্যাটফর্মের জন্য নেটিভ এবং ক্রস-প্ল্যাটফর্ম মোবাইল অ্যাপ্লিকেশন।",
    "services.feat_api": "এপিআই ডেভেলপমেন্ট", "services.feat_api_desc": "বিদ্যমান সিস্টেমের সাথে নিরবচ্ছিন্ন ইন্টিগ্রেশনের জন্য শক্তিশালী RESTful এবং GraphQL API।",
    "services.feat_payment": "পেমেন্ট সিস্টেম", "services.feat_payment_desc": "নিরাপদ পেমেন্ট গেটওয়ে, লেনদেন প্রক্রিয়াকরণ এবং আর্থিক ব্যবস্থাপনা টুল।",
    "services.feat_banking": "ব্যাংকিং সমাধান", "services.feat_banking_desc": "কোর ব্যাংকিং সিস্টেম, মোবাইল ব্যাংকিং অ্যাপ এবং আর্থিক রিপোর্টিং প্ল্যাটফর্ম।",
    "services.feat_compliance": "কমপ্লায়েন্স টুল", "services.feat_compliance_desc": "বিভিন্ন শিল্পের জন্য নিয়ন্ত্রক সম্মতি ব্যবস্থাপনা এবং অডিট ট্রেইল সিস্টেম।",
    "services.feat_ml": "মেশিন লার্নিং", "services.feat_ml_desc": "প্রেডিক্টিভ অ্যানালিটিক্স, রিকমেন্ডেশন সিস্টেম এবং অটোমেশনের জন্য কাস্টম ML মডেল।",
    "services.feat_analytics": "ডেটা অ্যানালিটিক্স", "services.feat_analytics_desc": "এআই-চালিত বিজনেস ইন্টেলিজেন্স, ডেটা ভিজ্যুয়ালাইজেশন এবং রিপোর্টিং ড্যাশবোর্ড।",
    "services.feat_chatbot": "চ্যাটবট ও এনএলপি", "services.feat_chatbot_desc": "বুদ্ধিমান চ্যাটবট, ভয়েস অ্যাসিস্ট্যান্ট এবং ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং সমাধান।",
    // Blog
    "blog.badge": "আমাদের ব্লগ", "blog.title": "অন্তর্দৃষ্টি ও", "blog.title_highlight": "আপডেট",
    "blog.subtitle": "প্রযুক্তি, সফটওয়্যার ডেভেলপমেন্ট এবং ডিজিটাল রূপান্তরের সর্বশেষ প্রবণতা সম্পর্কে আপডেট থাকুন।",
    "blog.loading": "পোস্ট লোড হচ্ছে...", "blog.no_posts": "এখনো কোনো ব্লগ পোস্ট প্রকাশিত হয়নি।",
    "blog.read_more": "আরও পড়ুন", "blog.contact_us": "যোগাযোগ করুন",
    "blog.stay_updated": "আপডেট থাকুন", "blog.stay_updated_desc": "নতুন পোস্ট এবং প্রযুক্তি অন্তর্দৃষ্টি সম্পর্কে আপডেট পেতে চান?", "blog.subscribe": "আপডেটে সাবস্ক্রাইব করুন",
    // Portfolio
    "portfolio.badge": "আমাদের পোর্টফোলিও", "portfolio.title": "কেস স্টাডি ও", "portfolio.title_highlight": "সাফল্যের গল্প",
    "portfolio.subtitle": "আমাদের সম্পন্ন প্রকল্পগুলো দেখুন এবং জানুন কিভাবে আমরা ব্যবসাগুলোকে রূপান্তর করেছি।",
    "portfolio.loading": "প্রকল্প লোড হচ্ছে...", "portfolio.coming_soon": "পোর্টফোলিও শীঘ্রই আসছে!",
    "portfolio.discuss_project": "আপনার প্রকল্প আলোচনা করুন", "portfolio.preview": "প্রিভিউ",
    "portfolio.view_case_study": "কেস স্টাডি দেখুন", "portfolio.get_quote": "কোটেশন নিন",
    "portfolio.cta_title": "একটি প্রকল্প মনে আছে?", "portfolio.cta_desc": "আমাদের দক্ষতা দিয়ে আপনার দৃষ্টিভঙ্গি বাস্তবায়নে কিভাবে সাহায্য করতে পারি তা আলোচনা করি।",
    "portfolio.cta_start": "আপনার প্রকল্প শুরু করুন",
    // Demo
    "demo.badge": "প্রকল্প শোকেস", "demo.title": "আমাদের অন্বেষণ করুন", "demo.title_highlight": "প্রকল্প শোকেস",
    "demo.subtitle": "আমাদের সফল প্রকল্পের পোর্টফোলিও আবিষ্কার করুন।",
    "demo.search_placeholder": "নাম বা বিবরণ দিয়ে প্রকল্প খুঁজুন...", "demo.all": "সকল প্রকল্প", "demo.featured": "বৈশিষ্ট্যযুক্ত",
    "demo.no_demos": "প্রকল্প শীঘ্রই আসছে", "demo.loading": "প্রকল্প লোড হচ্ছে...",
    "demo.view_demo": "ডেমো দেখুন", "demo.quote": "কোটেশন", "demo.views": "ভিউ",
    "demo.no_match": "মিলে যাওয়া প্রকল্প নেই", "demo.no_match_desc": "আপনার অনুসন্ধান সামঞ্জস্য করুন।",
    "demo.clear_search": "সার্চ মুছুন", "demo.request_demo": "ডেমো অনুরোধ করুন",
    "demo.custom_title": "কাস্টম সমাধান চান?", "demo.custom_desc": "আপনার নির্দিষ্ট প্রয়োজনীয়তার জন্য ব্যক্তিগত পরামর্শ নিন।",
    "demo.schedule": "পরামর্শ নিন", "demo.chat_whatsapp": "হোয়াটসঅ্যাপে চ্যাট",
    // Privacy / Terms
    "privacy.title": "গোপনীয়তা নীতি", "privacy.back": "হোমে ফিরুন", "terms.title": "সেবার শর্তাবলী", "terms.back": "হোমে ফিরুন",
  },
  ar: {
    "nav.home": "الرئيسية", "nav.about": "عن الشركة", "nav.services": "الخدمات", "nav.portfolio": "الأعمال", "nav.demo": "عرض تجريبي", "nav.blog": "المدونة", "nav.contact": "اتصل بنا",
    "cta.get_started": "ابدأ الآن",
    "footer.services": "الخدمات", "footer.company": "الشركة", "footer.contact": "اتصل بنا", "footer.rights": "جميع الحقوق محفوظة.", "footer.made_with": "صنع بـ",
    "footer.enterprise_solutions": "حلول المؤسسات", "footer.custom_development": "تطوير مخصص", "footer.security_finance": "الأمن والتمويل", "footer.ai_integration": "تكامل الذكاء الاصطناعي",
    "footer.about_us": "من نحن", "footer.privacy": "سياسة الخصوصية", "footer.terms": "شروط الخدمة",
    "hero.badge": "ابتكار الغد، اليوم", "hero.title1": "حوّل أعمالك", "hero.title2": "التجارية", "hero.title2_suffix": "مع", "hero.title3": "تكنولوجيا متطورة",
    "hero.subtitle": "نقدم حلول برمجية مبتكرة وأنظمة ذكاء اصطناعي واستشارات تقنية متخصصة.",
    "hero.cta_project": "ابدأ مشروعك", "hero.cta_demo": "شاهد العروض",
    "hero.stat_projects": "مشروع منجز", "hero.stat_satisfaction": "رضا العملاء", "hero.stat_experts": "خبير في الفريق",
    "hero.scroll": "تمرير", "hero.tag_software": "تطوير البرمجيات", "hero.tag_ai": "حلول الذكاء الاصطناعي", "hero.tag_consulting": "استشارات تقنية", "hero.tag_cloud": "خدمات سحابية",
    "services.badge": "خدماتنا", "services.title": "ماذا", "services.title_highlight": "نقدم", "services.subtitle": "حلول تقنية شاملة لتسريع نمو أعمالك والتحول الرقمي.",
    "services.chat_now": "تحدث الآن", "services.view_all": "عرض جميع الخدمات",
    "services.enterprise": "حلول المؤسسات", "services.enterprise_desc": "أنظمة إدارة أعمال شاملة مصممة لمؤسستك.",
    "services.custom": "تطوير مخصص", "services.custom_desc": "حلول برمجية مخصصة لتلبية متطلباتك الفريدة.",
    "services.security": "الأمن والتمويل", "services.security_desc": "أنظمة مالية آمنة وحلول أمان جاهزة للامتثال.",
    "services.ai": "تكامل الذكاء الاصطناعي", "services.ai_desc": "استفد من الذكاء الاصطناعي لأتمتة وتحسين أعمالك.",
    "contact.badge": "تواصل معنا", "contact.title": "لنبني", "contact.title_highlight": "شيئاً رائعاً",
    "contact.subtitle": "مستعد لتحويل عملك بالتكنولوجيا المتطورة؟",
    "contact.email_us": "راسلنا", "contact.whatsapp": "واتساب", "contact.location": "الموقع",
    "contact.form_title": "أرسل لنا رسالة", "contact.form_subtitle": "سنرد خلال 24 ساعة",
    "contact.name": "اسمك", "contact.email": "البريد الإلكتروني", "contact.phone": "رقم الهاتف", "contact.subject": "الموضوع",
    "contact.message": "رسالتك", "contact.message_placeholder": "أخبرنا عن مشروعك...",
    "contact.send": "إرسال الرسالة", "contact.sending": "جارِ الإرسال...",
    "contact.success_title": "تم الإرسال!", "contact.success_desc": "سنتواصل معك في أقرب وقت.",
    "contact.error": "فشل الإرسال. حاول مرة أخرى.", "contact.characters": "حرف",
    "contact.page_badge": "اتصل بنا", "contact.page_title": "لنبدأ", "contact.page_title_highlight": "محادثة",
    "contact.page_subtitle": "لديك مشروع في ذهنك؟ نحب أن نسمع منك.",
    "contact.visit_us": "زرنا", "contact.business_hours": "ساعات العمل", "contact.hours_value": "الأحد - الخميس: 9ص - 6م", "contact.call_us": "اتصل بنا",
    // About
    "about.badge": "من نحن", "about.title": "بناء مستقبل", "about.title_highlight": "التكنولوجيا", "about.subtitle": "engineersTech شركة تطوير برمجيات رائدة في بنغلاديش.",
    "about.mission_badge": "مهمتنا", "about.mission_title": "تمكين الأعمال من خلال التكنولوجيا",
    "about.mission_desc": "في engineersTech نؤمن بالقوة التحويلية للتكنولوجيا.",
    "about.mission_1": "برمجيات مخصصة لاحتياجاتك", "about.mission_2": "حلول قابلة للتوسع تنمو مع عملك",
    "about.mission_3": "دعم وصيانة على مدار الساعة", "about.mission_4": "منهجية تطوير رشيقة لتسليم أسرع",
    "about.values_badge": "قيمنا", "about.values_title": "ما يحركنا",
    "about.value_innovation": "الابتكار أولاً", "about.value_innovation_desc": "ندفع حدود التكنولوجيا باستمرار.",
    "about.value_client": "التركيز على العميل", "about.value_client_desc": "نجاحك هو أولويتنا.",
    "about.value_excellence": "التميز", "about.value_excellence_desc": "نحافظ على أعلى معايير الجودة.",
    "about.value_integrity": "النزاهة", "about.value_integrity_desc": "الشفافية والصدق أساس علاقاتنا.",
    "about.team_badge": "فريقنا", "about.team_title": "تعرف على الخبراء",
    "about.cta_title": "مستعد للعمل معنا؟", "about.cta_desc": "لنناقش كيف يمكننا تحويل عملك بحلولنا التقنية.",
    "about.cta_button": "تواصل معنا", "about.cta_services": "خدماتنا",
    "about.stat_projects": "مشروع مكتمل", "about.stat_clients": "عميل سعيد", "about.stat_years": "سنوات خبرة", "about.stat_support": "دعم متاح",
    // Services page
    "services.page_badge": "خدماتنا", "services.page_title": "حلول مؤسسية لـ", "services.page_title_highlight": "الأعمال الحديثة",
    "services.page_subtitle": "من تطوير البرمجيات المخصصة إلى تكامل الذكاء الاصطناعي.",
    "services.free_consultation": "احصل على استشارة مجانية", "services.discuss_whatsapp": "ناقش على واتساب", "services.learn_more": "اعرف المزيد",
    "services.cta_title": "مستعد لتحويل عملك؟", "services.cta_desc": "لنناقش كيف يمكن لحلولنا مساعدتك.",
    "services.cta_start": "ابدأ مشروعك", "services.cta_view_work": "شاهد أعمالنا",
    "services.feat_hrm": "نظام الموارد البشرية", "services.feat_hrm_desc": "إدارة شاملة للموارد البشرية مع الرواتب والحضور وإدارة الإجازات.",
    "services.feat_crm": "نظام إدارة العملاء", "services.feat_crm_desc": "إدارة علاقات العملاء لتعزيز المبيعات وتتبع العملاء المحتملين.",
    "services.feat_erp": "نظام تخطيط الموارد", "services.feat_erp_desc": "تخطيط موارد المؤسسة لعمليات سلسة عبر جميع الأقسام.",
    "services.feat_web": "تطبيقات الويب", "services.feat_web_desc": "تطبيقات ويب حديثة وسريعة الاستجابة باستخدام أحدث التقنيات.",
    "services.feat_mobile": "تطبيقات الجوال", "services.feat_mobile_desc": "تطبيقات جوال أصلية ومتعددة المنصات لنظامي iOS و Android.",
    "services.feat_api": "تطوير واجهات البرمجة", "services.feat_api_desc": "واجهات برمجة قوية للتكامل السلس مع الأنظمة الحالية.",
    "services.feat_payment": "أنظمة الدفع", "services.feat_payment_desc": "بوابات دفع آمنة ومعالجة المعاملات وأدوات الإدارة المالية.",
    "services.feat_banking": "حلول مصرفية", "services.feat_banking_desc": "أنظمة مصرفية أساسية وتطبيقات مصرفية متنقلة.",
    "services.feat_compliance": "أدوات الامتثال", "services.feat_compliance_desc": "إدارة الامتثال التنظيمي وأنظمة مسار التدقيق.",
    "services.feat_ml": "التعلم الآلي", "services.feat_ml_desc": "نماذج تعلم آلي مخصصة للتحليلات التنبؤية والأتمتة.",
    "services.feat_analytics": "تحليل البيانات", "services.feat_analytics_desc": "ذكاء أعمال مدعوم بالذكاء الاصطناعي ولوحات تقارير.",
    "services.feat_chatbot": "روبوتات المحادثة", "services.feat_chatbot_desc": "روبوتات محادثة ذكية ومعالجة اللغة الطبيعية.",
    // Blog
    "blog.badge": "مدونتنا", "blog.title": "رؤى و", "blog.title_highlight": "تحديثات",
    "blog.subtitle": "ابق على اطلاع بأحدث الاتجاهات في التكنولوجيا والتحول الرقمي.",
    "blog.loading": "جاري تحميل المقالات...", "blog.no_posts": "لم يتم نشر أي مقالات بعد.",
    "blog.read_more": "اقرأ المزيد", "blog.contact_us": "اتصل بنا",
    "blog.stay_updated": "ابق على اطلاع", "blog.stay_updated_desc": "تريد تلقي تحديثات حول المقالات الجديدة؟", "blog.subscribe": "اشترك في التحديثات",
    // Portfolio
    "portfolio.badge": "أعمالنا", "portfolio.title": "دراسات حالة و", "portfolio.title_highlight": "قصص نجاح",
    "portfolio.subtitle": "استكشف مشاريعنا المكتملة وشاهد كيف ساعدنا الشركات في التحول.",
    "portfolio.loading": "جاري تحميل المشاريع...", "portfolio.coming_soon": "المحفظة قادمة قريباً!",
    "portfolio.discuss_project": "ناقش مشروعك", "portfolio.preview": "معاينة",
    "portfolio.view_case_study": "عرض دراسة الحالة", "portfolio.get_quote": "احصل على عرض سعر",
    "portfolio.cta_title": "لديك مشروع في ذهنك؟", "portfolio.cta_desc": "لنناقش كيف يمكننا المساعدة في تحقيق رؤيتك.",
    "portfolio.cta_start": "ابدأ مشروعك",
    // Demo
    "demo.badge": "معرض المشاريع", "demo.title": "استكشف", "demo.title_highlight": "معرض مشاريعنا",
    "demo.subtitle": "اكتشف محفظة مشاريعنا الناجحة.",
    "demo.search_placeholder": "ابحث عن المشاريع...", "demo.all": "جميع المشاريع", "demo.featured": "مميز",
    "demo.no_demos": "المشاريع قادمة قريباً", "demo.loading": "جاري تحميل المشاريع...",
    "demo.view_demo": "عرض تجريبي", "demo.quote": "عرض سعر", "demo.views": "مشاهدات",
    "demo.no_match": "لا توجد مشاريع مطابقة", "demo.no_match_desc": "حاول تعديل البحث.",
    "demo.clear_search": "مسح البحث", "demo.request_demo": "طلب عرض تجريبي",
    "demo.custom_title": "تريد حلاً مخصصاً؟", "demo.custom_desc": "حدد موعداً لاستشارة مخصصة.",
    "demo.schedule": "حجز استشارة", "demo.chat_whatsapp": "محادثة واتساب",
    "privacy.title": "سياسة الخصوصية", "privacy.back": "العودة للرئيسية", "terms.title": "شروط الخدمة", "terms.back": "العودة للرئيسية",
  },
  hi: {
    "nav.home": "होम", "nav.about": "हमारे बारे में", "nav.services": "सेवाएं", "nav.portfolio": "पोर्टफोलियो", "nav.demo": "डेमो", "nav.blog": "ब्लॉग", "nav.contact": "संपर्क",
    "cta.get_started": "शुरू करें",
    "footer.services": "सेवाएं", "footer.company": "कंपनी", "footer.contact": "संपर्क", "footer.rights": "सर्वाधिकार सुरक्षित।", "footer.made_with": "बनाया गया",
    "footer.enterprise_solutions": "एंटरप्राइज समाधान", "footer.custom_development": "कस्टम विकास", "footer.security_finance": "सुरक्षा और वित्त", "footer.ai_integration": "एआई एकीकरण",
    "footer.about_us": "हमारे बारे में", "footer.privacy": "गोपनीयता नीति", "footer.terms": "सेवा की शर्तें",
    "hero.badge": "आज ही कल का नवाचार", "hero.title1": "अपने व्यापार को", "hero.title2": "बदलें", "hero.title2_suffix": "के साथ", "hero.title3": "अत्याधुनिक तकनीक",
    "hero.subtitle": "हम नवीन सॉफ्टवेयर समाधान, एआई-संचालित प्रणालियां और विशेषज्ञ आईटी परामर्श प्रदान करते हैं।",
    "hero.cta_project": "अपना प्रोजेक्ट शुरू करें", "hero.cta_demo": "लाइव डेमो देखें",
    "hero.stat_projects": "प्रोजेक्ट पूरे", "hero.stat_satisfaction": "ग्राहक संतुष्टि", "hero.stat_experts": "विशेषज्ञ",
    "hero.scroll": "स्क्रॉल", "hero.tag_software": "सॉफ्टवेयर विकास", "hero.tag_ai": "एआई समाधान", "hero.tag_consulting": "आईटी परामर्श", "hero.tag_cloud": "क्लाउड सेवाएं",
    "services.badge": "हमारी सेवाएं", "services.title": "हम क्या", "services.title_highlight": "प्रदान करते हैं", "services.subtitle": "आपके व्यापार विकास को तेज करने के लिए व्यापक तकनीकी समाधान।",
    "services.chat_now": "चैट करें", "services.view_all": "सभी सेवाएं देखें",
    "services.enterprise": "एंटरप्राइज समाधान", "services.enterprise_desc": "आपके संगठन के लिए तैयार व्यापक व्यवसाय प्रबंधन प्रणालियां।",
    "services.custom": "कस्टम विकास", "services.custom_desc": "आपकी अनूठी व्यावसायिक आवश्यकताओं के अनुरूप सॉफ्टवेयर समाधान।",
    "services.security": "सुरक्षा और वित्त", "services.security_desc": "सुरक्षित वित्तीय प्रणालियां और अनुपालन-तैयार सुरक्षा समाधान।",
    "services.ai": "एआई एकीकरण", "services.ai_desc": "अपने व्यवसाय को स्वचालित और अनुकूलित करने के लिए कृत्रिम बुद्धिमत्ता।",
    "contact.badge": "संपर्क करें", "contact.title": "आइए बनाएं", "contact.title_highlight": "कुछ शानदार",
    "contact.subtitle": "अत्याधुनिक तकनीक से अपने व्यवसाय को बदलने के लिए तैयार?",
    "contact.email_us": "ईमेल करें", "contact.whatsapp": "व्हाट्सएप", "contact.location": "स्थान",
    "contact.form_title": "हमें संदेश भेजें", "contact.form_subtitle": "हम 24 घंटे में जवाब देंगे",
    "contact.name": "आपका नाम", "contact.email": "ईमेल पता", "contact.phone": "फोन नंबर", "contact.subject": "विषय",
    "contact.message": "आपका संदेश", "contact.message_placeholder": "अपने प्रोजेक्ट के बारे में बताएं...",
    "contact.send": "संदेश भेजें", "contact.sending": "भेजा जा रहा है...",
    "contact.success_title": "संदेश भेजा गया!", "contact.success_desc": "हम जल्द ही आपसे संपर्क करेंगे।",
    "contact.error": "संदेश भेजने में विफल। पुनः प्रयास करें।", "contact.characters": "अक्षर",
    "contact.page_badge": "संपर्क", "contact.page_title": "शुरू करें एक", "contact.page_title_highlight": "बातचीत",
    "contact.page_subtitle": "कोई प्रोजेक्ट है? हम आपसे सुनना चाहेंगे।",
    "contact.visit_us": "हमसे मिलें", "contact.business_hours": "कार्य समय", "contact.hours_value": "रवि - गुरु: सुबह 9 - शाम 6", "contact.call_us": "कॉल करें",
    // About
    "about.badge": "हमारे बारे में", "about.title": "प्रौद्योगिकी का भविष्य", "about.title_highlight": "निर्माण", "about.subtitle": "engineersTech बांग्लादेश की एक अग्रणी सॉफ्टवेयर डेवेलपमेंट कंपनी है।",
    "about.mission_badge": "हमारा मिशन", "about.mission_title": "प्रौद्योगिकी के माध्यम से व्यवसायों को सशक्त बनाना",
    "about.mission_desc": "engineersTech में हम प्रौद्योगिकी की परिवर्तनकारी शक्ति में विश्वास करते हैं।",
    "about.mission_1": "आपकी अनूठी जरूरतों के अनुसार कस्टम सॉफ्टवेयर", "about.mission_2": "आपके व्यवसाय के साथ बढ़ने वाले स्केलेबल समाधान",
    "about.mission_3": "24/7 समर्पित सहायता और रखरखाव", "about.mission_4": "तेजी से डिलीवरी के लिए एजाइल डेवेलपमेंट",
    "about.values_badge": "हमारे मूल्य", "about.values_title": "हमें क्या प्रेरित करता है",
    "about.value_innovation": "नवाचार पहले", "about.value_innovation_desc": "हम लगातार प्रौद्योगिकी की सीमाओं को आगे बढ़ाते हैं।",
    "about.value_client": "ग्राहक-केंद्रित", "about.value_client_desc": "आपकी सफलता हमारी प्राथमिकता है।",
    "about.value_excellence": "उत्कृष्टता", "about.value_excellence_desc": "हर प्रोजेक्ट में उच्चतम गुणवत्ता मानक बनाए रखते हैं।",
    "about.value_integrity": "ईमानदारी", "about.value_integrity_desc": "पारदर्शिता और ईमानदारी हमारे व्यापारिक संबंधों की नींव है।",
    "about.team_badge": "हमारी टीम", "about.team_title": "विशेषज्ञों से मिलें",
    "about.cta_title": "हमारे साथ काम करने के लिए तैयार?", "about.cta_desc": "हमारी तकनीकी समाधानों से आपके व्यवसाय को कैसे बदल सकते हैं, चर्चा करें।",
    "about.cta_button": "संपर्क करें", "about.cta_services": "हमारी सेवाएं",
    "about.stat_projects": "प्रोजेक्ट पूरे", "about.stat_clients": "खुश ग्राहक", "about.stat_years": "वर्षों का अनुभव", "about.stat_support": "सहायता उपलब्ध",
    "services.page_badge": "हमारी सेवाएं", "services.page_title": "आधुनिक व्यापार के लिए", "services.page_title_highlight": "एंटरप्राइज समाधान",
    "services.page_subtitle": "कस्टम सॉफ्टवेयर विकास से एआई एकीकरण तक, व्यापक तकनीकी समाधान।",
    "services.free_consultation": "मुफ्त परामर्श प्राप्त करें", "services.discuss_whatsapp": "व्हाट्सएप पर चर्चा करें", "services.learn_more": "और जानें",
    "services.cta_title": "अपना व्यवसाय बदलने के लिए तैयार?", "services.cta_desc": "हमारे समाधान आपके लक्ष्य कैसे प्राप्त कर सकते हैं, चर्चा करें।",
    "services.cta_start": "अपना प्रोजेक्ट शुरू करें", "services.cta_view_work": "हमारा काम देखें",
    "services.feat_hrm": "एचआरएम सिस्टम", "services.feat_hrm_desc": "वेतन, उपस्थिति, छुट्टी प्रबंधन और प्रदर्शन ट्रैकिंग के साथ पूर्ण मानव संसाधन प्रबंधन।",
    "services.feat_crm": "सीआरएम सिस्टम", "services.feat_crm_desc": "बिक्री बढ़ाने और ग्राहक बनाए रखने के लिए ग्राहक संबंध प्रबंधन।",
    "services.feat_erp": "ईआरपी सिस्टम", "services.feat_erp_desc": "सभी विभागों में निर्बाध व्यावसायिक संचालन के लिए एंटरप्राइज रिसोर्स प्लानिंग।",
    "services.feat_web": "वेब एप्लिकेशन", "services.feat_web_desc": "React, Next.js और अन्य अत्याधुनिक तकनीकों का उपयोग करते हुए आधुनिक वेब एप्लिकेशन।",
    "services.feat_mobile": "मोबाइल ऐप", "services.feat_mobile_desc": "iOS और Android के लिए नेटिव और क्रॉस-प्लेटफॉर्म मोबाइल एप्लिकेशन।",
    "services.feat_api": "एपीआई डेवेलपमेंट", "services.feat_api_desc": "मौजूदा सिस्टम के साथ निर्बाध एकीकरण के लिए मजबूत API।",
    "services.feat_payment": "भुगतान प्रणाली", "services.feat_payment_desc": "सुरक्षित भुगतान गेटवे और वित्तीय प्रबंधन उपकरण।",
    "services.feat_banking": "बैंकिंग समाधान", "services.feat_banking_desc": "कोर बैंकिंग सिस्टम और मोबाइल बैंकिंग ऐप।",
    "services.feat_compliance": "अनुपालन उपकरण", "services.feat_compliance_desc": "विभिन्न उद्योगों के लिए नियामक अनुपालन प्रबंधन।",
    "services.feat_ml": "मशीन लर्निंग", "services.feat_ml_desc": "प्रेडिक्टिव एनालिटिक्स और ऑटोमेशन के लिए कस्टम ML मॉडल।",
    "services.feat_analytics": "डेटा एनालिटिक्स", "services.feat_analytics_desc": "एआई-संचालित बिजनेस इंटेलिजेंस और रिपोर्टिंग डैशबोर्ड।",
    "services.feat_chatbot": "चैटबॉट और एनएलपी", "services.feat_chatbot_desc": "बुद्धिमान चैटबॉट और नेचुरल लैंग्वेज प्रोसेसिंग समाधान।",
    "blog.badge": "हमारा ब्लॉग", "blog.title": "अंतर्दृष्टि और", "blog.title_highlight": "अपडेट",
    "blog.subtitle": "प्रौद्योगिकी और डिजिटल परिवर्तन में नवीनतम रुझानों से अपडेट रहें।",
    "blog.loading": "पोस्ट लोड हो रहे हैं...", "blog.no_posts": "अभी तक कोई ब्लॉग पोस्ट प्रकाशित नहीं हुई।",
    "blog.read_more": "और पढ़ें", "blog.contact_us": "संपर्क करें",
    "blog.stay_updated": "अपडेट रहें", "blog.stay_updated_desc": "नई पोस्ट और तकनीकी अंतर्दृष्टि के बारे में अपडेट प्राप्त करना चाहते हैं?", "blog.subscribe": "अपडेट के लिए सदस्यता लें",
    "portfolio.badge": "हमारा पोर्टफोलियो", "portfolio.title": "केस स्टडी और", "portfolio.title_highlight": "सफलता की कहानियां",
    "portfolio.subtitle": "हमारे पूर्ण प्रोजेक्ट देखें।", "portfolio.loading": "प्रोजेक्ट लोड हो रहे हैं...",
    "portfolio.coming_soon": "पोर्टफोलियो जल्द आ रहा है!", "portfolio.discuss_project": "अपने प्रोजेक्ट पर चर्चा करें",
    "portfolio.preview": "प्रीव्यू", "portfolio.view_case_study": "केस स्टडी देखें", "portfolio.get_quote": "कोटेशन लें",
    "portfolio.cta_title": "कोई प्रोजेक्ट है?", "portfolio.cta_desc": "हमारी विशेषज्ञता से आपकी दृष्टि को साकार करने में कैसे मदद कर सकते हैं।",
    "portfolio.cta_start": "अपना प्रोजेक्ट शुरू करें",
    "demo.badge": "प्रोजेक्ट शोकेस", "demo.title": "हमारा अन्वेषण करें", "demo.title_highlight": "प्रोजेक्ट शोकेस",
    "demo.subtitle": "हमारे सफल प्रोजेक्ट का पोर्टफोलियो खोजें।",
    "demo.search_placeholder": "नाम या विवरण से प्रोजेक्ट खोजें...", "demo.all": "सभी प्रोजेक्ट", "demo.featured": "विशेष",
    "demo.no_demos": "प्रोजेक्ट जल्द आ रहे हैं", "demo.loading": "प्रोजेक्ट लोड हो रहे हैं...",
    "demo.view_demo": "डेमो देखें", "demo.quote": "कोटेशन", "demo.views": "व्यूज",
    "demo.no_match": "मिलान नहीं मिला", "demo.no_match_desc": "अपनी खोज समायोजित करें।",
    "demo.clear_search": "खोज साफ करें", "demo.request_demo": "डेमो अनुरोध",
    "demo.custom_title": "कस्टम समाधान चाहिए?", "demo.custom_desc": "व्यक्तिगत परामर्श शेड्यूल करें।",
    "demo.schedule": "परामर्श शेड्यूल करें", "demo.chat_whatsapp": "व्हाट्सएप पर चैट",
    "privacy.title": "गोपनीयता नीति", "privacy.back": "होम पर वापस", "terms.title": "सेवा की शर्तें", "terms.back": "होम पर वापस",
  },
  es: {
    "nav.home": "Inicio", "nav.about": "Nosotros", "nav.services": "Servicios", "nav.portfolio": "Portafolio", "nav.demo": "Demo", "nav.blog": "Blog", "nav.contact": "Contacto",
    "cta.get_started": "Empezar",
    "footer.services": "Servicios", "footer.company": "Empresa", "footer.contact": "Contacto", "footer.rights": "Todos los derechos reservados.", "footer.made_with": "Hecho con",
    "footer.enterprise_solutions": "Soluciones Empresariales", "footer.custom_development": "Desarrollo a Medida", "footer.security_finance": "Seguridad y Finanzas", "footer.ai_integration": "Integración de IA",
    "footer.about_us": "Sobre Nosotros", "footer.privacy": "Política de Privacidad", "footer.terms": "Términos de Servicio",
    "hero.badge": "Innovando el Mañana, Hoy", "hero.title1": "Transforma Tu", "hero.title2": "Negocio", "hero.title2_suffix": "con", "hero.title3": "Tecnología de Vanguardia",
    "hero.subtitle": "Ofrecemos soluciones de software innovadoras, sistemas de IA y consultoría TI experta.",
    "hero.cta_project": "Inicia Tu Proyecto", "hero.cta_demo": "Ver Demos",
    "hero.stat_projects": "Proyectos Entregados", "hero.stat_satisfaction": "Satisfacción del Cliente", "hero.stat_experts": "Expertos",
    "hero.scroll": "Desplazar", "hero.tag_software": "Desarrollo de Software", "hero.tag_ai": "Soluciones IA", "hero.tag_consulting": "Consultoría TI", "hero.tag_cloud": "Servicios Cloud",
    "services.badge": "Nuestros Servicios", "services.title": "Qué", "services.title_highlight": "Ofrecemos", "services.subtitle": "Soluciones tecnológicas integrales para acelerar el crecimiento de tu negocio.",
    "services.chat_now": "Chatear", "services.view_all": "Ver Todos los Servicios",
    "services.enterprise": "Soluciones Empresariales", "services.enterprise_desc": "Sistemas integrales de gestión empresarial.",
    "services.custom": "Desarrollo a Medida", "services.custom_desc": "Soluciones de software a medida para tu negocio.",
    "services.security": "Seguridad y Finanzas", "services.security_desc": "Sistemas financieros seguros y soluciones de cumplimiento.",
    "services.ai": "Integración de IA", "services.ai_desc": "Aprovecha la IA para automatizar y optimizar tu negocio.",
    "contact.badge": "Contáctanos", "contact.title": "Construyamos", "contact.title_highlight": "Algo Grandioso",
    "contact.subtitle": "¿Listo para transformar tu negocio con tecnología de vanguardia?",
    "contact.email_us": "Escríbenos", "contact.whatsapp": "WhatsApp", "contact.location": "Ubicación",
    "contact.form_title": "Envíanos un mensaje", "contact.form_subtitle": "Respondemos en 24 horas",
    "contact.name": "Tu Nombre", "contact.email": "Correo Electrónico", "contact.phone": "Teléfono", "contact.subject": "Asunto",
    "contact.message": "Tu Mensaje", "contact.message_placeholder": "Cuéntanos sobre tu proyecto...",
    "contact.send": "Enviar Mensaje", "contact.sending": "Enviando...",
    "contact.success_title": "¡Mensaje enviado!", "contact.success_desc": "Te contactaremos lo antes posible.",
    "contact.error": "Error al enviar. Inténtalo de nuevo.", "contact.characters": "caracteres",
    "contact.page_badge": "Contacto", "contact.page_title": "Iniciemos una", "contact.page_title_highlight": "Conversación",
    "contact.page_subtitle": "¿Tienes un proyecto en mente? Nos encantaría escucharte.",
    "contact.visit_us": "Visítanos", "contact.business_hours": "Horario", "contact.hours_value": "Dom - Jue: 9AM - 6PM", "contact.call_us": "Llámanos",
    "about.badge": "Sobre Nosotros", "about.title": "Construyendo el Futuro de la", "about.title_highlight": "Tecnología", "about.subtitle": "engineersTech es una empresa líder de desarrollo de software en Bangladesh.",
    "about.mission_badge": "Nuestra Misión", "about.mission_title": "Empoderando Negocios a través de la Tecnología",
    "about.mission_desc": "En engineersTech creemos en el poder transformador de la tecnología.",
    "about.mission_1": "Software personalizado para tus necesidades", "about.mission_2": "Soluciones escalables que crecen con tu negocio",
    "about.mission_3": "Soporte dedicado 24/7", "about.mission_4": "Metodología ágil para entregas más rápidas",
    "about.values_badge": "Nuestros Valores", "about.values_title": "Lo Que Nos Impulsa",
    "about.value_innovation": "Innovación Primero", "about.value_innovation_desc": "Empujamos los límites de la tecnología constantemente.",
    "about.value_client": "Centrado en el Cliente", "about.value_client_desc": "Tu éxito es nuestra prioridad.",
    "about.value_excellence": "Excelencia", "about.value_excellence_desc": "Mantenemos los más altos estándares de calidad.",
    "about.value_integrity": "Integridad", "about.value_integrity_desc": "Transparencia y honestidad son la base de nuestras relaciones.",
    "about.team_badge": "Nuestro Equipo", "about.team_title": "Conoce a los Expertos",
    "about.cta_title": "¿Listo para Trabajar con Nosotros?", "about.cta_desc": "Discutamos cómo transformar tu negocio con nuestras soluciones.",
    "about.cta_button": "Contáctanos", "about.cta_services": "Nuestros Servicios",
    "about.stat_projects": "Proyectos Completados", "about.stat_clients": "Clientes Felices", "about.stat_years": "Años de Experiencia", "about.stat_support": "Soporte Disponible",
    "services.page_badge": "Nuestros Servicios", "services.page_title": "Soluciones Empresariales para", "services.page_title_highlight": "Negocios Modernos",
    "services.page_subtitle": "Desde desarrollo de software hasta integración de IA.", "services.free_consultation": "Consulta Gratuita",
    "services.discuss_whatsapp": "Discutir en WhatsApp", "services.learn_more": "Más Información",
    "services.cta_title": "¿Listo para Transformar tu Negocio?", "services.cta_desc": "Discutamos cómo nuestras soluciones pueden ayudarte.",
    "services.cta_start": "Inicia tu Proyecto", "services.cta_view_work": "Ver Nuestro Trabajo",
    "services.feat_hrm": "Sistema HRM", "services.feat_hrm_desc": "Gestión completa de recursos humanos con nómina y seguimiento.",
    "services.feat_crm": "Sistema CRM", "services.feat_crm_desc": "Gestión de relaciones con clientes para impulsar ventas.",
    "services.feat_erp": "Sistema ERP", "services.feat_erp_desc": "Planificación de recursos empresariales para operaciones fluidas.",
    "services.feat_web": "Aplicaciones Web", "services.feat_web_desc": "Aplicaciones web modernas con tecnologías de vanguardia.",
    "services.feat_mobile": "Apps Móviles", "services.feat_mobile_desc": "Aplicaciones móviles nativas y multiplataforma.",
    "services.feat_api": "Desarrollo API", "services.feat_api_desc": "APIs robustas para integración con sistemas existentes.",
    "services.feat_payment": "Sistemas de Pago", "services.feat_payment_desc": "Pasarelas de pago seguras y herramientas financieras.",
    "services.feat_banking": "Soluciones Bancarias", "services.feat_banking_desc": "Sistemas bancarios centrales y apps de banca móvil.",
    "services.feat_compliance": "Herramientas de Cumplimiento", "services.feat_compliance_desc": "Gestión de cumplimiento normativo y auditoría.",
    "services.feat_ml": "Machine Learning", "services.feat_ml_desc": "Modelos ML personalizados para análisis predictivo.",
    "services.feat_analytics": "Analítica de Datos", "services.feat_analytics_desc": "Inteligencia empresarial impulsada por IA.",
    "services.feat_chatbot": "Chatbots y NLP", "services.feat_chatbot_desc": "Chatbots inteligentes y procesamiento de lenguaje natural.",
    "blog.badge": "Nuestro Blog", "blog.title": "Perspectivas y", "blog.title_highlight": "Actualizaciones",
    "blog.subtitle": "Mantente al día con las últimas tendencias en tecnología.", "blog.loading": "Cargando publicaciones...",
    "blog.no_posts": "Aún no hay publicaciones.", "blog.read_more": "Leer Más", "blog.contact_us": "Contáctanos",
    "blog.stay_updated": "Mantente Actualizado", "blog.stay_updated_desc": "¿Quieres recibir actualizaciones?", "blog.subscribe": "Suscríbete",
    "portfolio.badge": "Nuestro Portafolio", "portfolio.title": "Casos de Éxito y", "portfolio.title_highlight": "Historias de Éxito",
    "portfolio.subtitle": "Explora nuestros proyectos completados.", "portfolio.loading": "Cargando proyectos...",
    "portfolio.coming_soon": "¡Portafolio próximamente!", "portfolio.discuss_project": "Discute tu Proyecto",
    "portfolio.preview": "Vista Previa", "portfolio.view_case_study": "Ver Caso de Estudio", "portfolio.get_quote": "Obtener Cotización",
    "portfolio.cta_title": "¿Tienes un Proyecto en Mente?", "portfolio.cta_desc": "Discutamos cómo dar vida a tu visión.",
    "portfolio.cta_start": "Inicia tu Proyecto",
    "demo.badge": "Vitrina de Proyectos", "demo.title": "Explora Nuestra", "demo.title_highlight": "Vitrina de Proyectos",
    "demo.subtitle": "Descubre nuestro portafolio de proyectos exitosos.",
    "demo.search_placeholder": "Buscar proyectos...", "demo.all": "Todos", "demo.featured": "Destacado",
    "demo.no_demos": "Proyectos Próximamente", "demo.loading": "Cargando...",
    "demo.view_demo": "Ver Demo", "demo.quote": "Cotización", "demo.views": "vistas",
    "demo.no_match": "Sin Coincidencias", "demo.no_match_desc": "Ajusta tu búsqueda.",
    "demo.clear_search": "Limpiar Búsqueda", "demo.request_demo": "Solicitar Demo",
    "demo.custom_title": "¿Quieres una Solución Personalizada?", "demo.custom_desc": "Agenda una consulta personalizada.",
    "demo.schedule": "Agendar Consulta", "demo.chat_whatsapp": "Chatear en WhatsApp",
    "privacy.title": "Política de Privacidad", "privacy.back": "Volver al Inicio", "terms.title": "Términos de Servicio", "terms.back": "Volver al Inicio",
  },
  fr: {
    "nav.home": "Accueil", "nav.about": "À propos", "nav.services": "Services", "nav.portfolio": "Portfolio", "nav.demo": "Démo", "nav.blog": "Blog", "nav.contact": "Contact",
    "cta.get_started": "Commencer",
    "footer.services": "Services", "footer.company": "Entreprise", "footer.contact": "Contact", "footer.rights": "Tous droits réservés.", "footer.made_with": "Fait avec",
    "footer.enterprise_solutions": "Solutions d'Entreprise", "footer.custom_development": "Développement Sur Mesure", "footer.security_finance": "Sécurité & Finance", "footer.ai_integration": "Intégration IA",
    "footer.about_us": "À Propos", "footer.privacy": "Politique de Confidentialité", "footer.terms": "Conditions d'Utilisation",
    "hero.badge": "Innover Demain, Aujourd'hui", "hero.title1": "Transformez Votre", "hero.title2": "Entreprise", "hero.title2_suffix": "avec", "hero.title3": "Technologie de Pointe",
    "hero.subtitle": "Nous fournissons des solutions logicielles innovantes, des systèmes IA et du conseil IT expert.",
    "hero.cta_project": "Démarrer Votre Projet", "hero.cta_demo": "Voir les Démos",
    "hero.stat_projects": "Projets Livrés", "hero.stat_satisfaction": "Satisfaction Client", "hero.stat_experts": "Experts",
    "hero.scroll": "Défiler", "hero.tag_software": "Développement Logiciel", "hero.tag_ai": "Solutions IA", "hero.tag_consulting": "Conseil IT", "hero.tag_cloud": "Services Cloud",
    "services.badge": "Nos Services", "services.title": "Ce Que Nous", "services.title_highlight": "Offrons", "services.subtitle": "Des solutions technologiques complètes pour accélérer la croissance de votre entreprise.",
    "services.chat_now": "Discuter", "services.view_all": "Voir Tous les Services",
    "services.enterprise": "Solutions d'Entreprise", "services.enterprise_desc": "Systèmes de gestion d'entreprise complets.",
    "services.custom": "Développement Sur Mesure", "services.custom_desc": "Solutions logicielles personnalisées pour votre entreprise.",
    "services.security": "Sécurité & Finance", "services.security_desc": "Systèmes financiers sécurisés et solutions de conformité.",
    "services.ai": "Intégration IA", "services.ai_desc": "Exploitez l'IA pour automatiser et optimiser votre entreprise.",
    "contact.badge": "Contactez-nous", "contact.title": "Construisons", "contact.title_highlight": "Quelque Chose de Grand",
    "contact.subtitle": "Prêt à transformer votre entreprise avec la technologie de pointe?",
    "contact.email_us": "Email", "contact.whatsapp": "WhatsApp", "contact.location": "Emplacement",
    "contact.form_title": "Envoyez-nous un message", "contact.form_subtitle": "Nous répondons sous 24h",
    "contact.name": "Votre Nom", "contact.email": "Adresse Email", "contact.phone": "Téléphone", "contact.subject": "Sujet",
    "contact.message": "Votre Message", "contact.message_placeholder": "Parlez-nous de votre projet...",
    "contact.send": "Envoyer", "contact.sending": "Envoi...",
    "contact.success_title": "Message envoyé!", "contact.success_desc": "Nous vous répondrons rapidement.",
    "contact.error": "Échec de l'envoi. Réessayez.", "contact.characters": "caractères",
    "contact.page_badge": "Contact", "contact.page_title": "Commençons une", "contact.page_title_highlight": "Conversation",
    "contact.page_subtitle": "Un projet en tête? Contactez-nous.",
    "contact.visit_us": "Visitez-nous", "contact.business_hours": "Horaires", "contact.hours_value": "Dim - Jeu: 9h - 18h", "contact.call_us": "Appelez-nous",
    "about.badge": "À Propos", "about.title": "Construire l'Avenir de la", "about.title_highlight": "Technologie", "about.subtitle": "engineersTech est une entreprise de développement logiciel de premier plan au Bangladesh.",
    "about.mission_badge": "Notre Mission", "about.mission_title": "Autonomiser les Entreprises par la Technologie",
    "about.mission_desc": "Chez engineersTech, nous croyons au pouvoir transformateur de la technologie.",
    "about.mission_1": "Logiciels personnalisés pour vos besoins", "about.mission_2": "Solutions évolutives qui grandissent avec votre entreprise",
    "about.mission_3": "Support dédié 24/7", "about.mission_4": "Méthodologie agile pour une livraison plus rapide",
    "about.values_badge": "Nos Valeurs", "about.values_title": "Ce Qui Nous Motive",
    "about.value_innovation": "Innovation d'Abord", "about.value_innovation_desc": "Nous repoussons les limites de la technologie.",
    "about.value_client": "Centré sur le Client", "about.value_client_desc": "Votre succès est notre priorité.",
    "about.value_excellence": "Excellence", "about.value_excellence_desc": "Nous maintenons les plus hauts standards de qualité.",
    "about.value_integrity": "Intégrité", "about.value_integrity_desc": "Transparence et honnêteté fondent nos relations.",
    "about.team_badge": "Notre Équipe", "about.team_title": "Rencontrez les Experts",
    "about.cta_title": "Prêt à Travailler avec Nous?", "about.cta_desc": "Discutons de comment transformer votre entreprise.",
    "about.cta_button": "Contactez-nous", "about.cta_services": "Nos Services",
    "about.stat_projects": "Projets Réalisés", "about.stat_clients": "Clients Satisfaits", "about.stat_years": "Années d'Expérience", "about.stat_support": "Support Disponible",
    "services.page_badge": "Nos Services", "services.page_title": "Solutions pour", "services.page_title_highlight": "Entreprises Modernes",
    "services.page_subtitle": "Du développement sur mesure à l'intégration IA.", "services.free_consultation": "Consultation Gratuite",
    "services.discuss_whatsapp": "Discuter sur WhatsApp", "services.learn_more": "En Savoir Plus",
    "services.cta_title": "Prêt à Transformer Votre Entreprise?", "services.cta_desc": "Discutons de comment nos solutions peuvent vous aider.",
    "services.cta_start": "Démarrer Votre Projet", "services.cta_view_work": "Voir Nos Réalisations",
    "services.feat_hrm": "Système HRM", "services.feat_hrm_desc": "Gestion complète des ressources humaines avec paie et suivi.",
    "services.feat_crm": "Système CRM", "services.feat_crm_desc": "Gestion de la relation client pour booster les ventes.",
    "services.feat_erp": "Système ERP", "services.feat_erp_desc": "Planification des ressources pour des opérations fluides.",
    "services.feat_web": "Applications Web", "services.feat_web_desc": "Applications web modernes avec technologies de pointe.",
    "services.feat_mobile": "Apps Mobiles", "services.feat_mobile_desc": "Applications mobiles natives et multiplateformes.",
    "services.feat_api": "Développement API", "services.feat_api_desc": "APIs robustes pour intégration avec les systèmes existants.",
    "services.feat_payment": "Systèmes de Paiement", "services.feat_payment_desc": "Passerelles de paiement sécurisées et outils financiers.",
    "services.feat_banking": "Solutions Bancaires", "services.feat_banking_desc": "Systèmes bancaires et applications mobiles bancaires.",
    "services.feat_compliance": "Outils de Conformité", "services.feat_compliance_desc": "Gestion de conformité réglementaire et audit.",
    "services.feat_ml": "Machine Learning", "services.feat_ml_desc": "Modèles ML personnalisés pour l'analyse prédictive.",
    "services.feat_analytics": "Analyse de Données", "services.feat_analytics_desc": "Intelligence d'affaires alimentée par l'IA.",
    "services.feat_chatbot": "Chatbots et NLP", "services.feat_chatbot_desc": "Chatbots intelligents et traitement du langage naturel.",
    "blog.badge": "Notre Blog", "blog.title": "Perspectives et", "blog.title_highlight": "Mises à Jour",
    "blog.subtitle": "Restez informé des dernières tendances technologiques.", "blog.loading": "Chargement...",
    "blog.no_posts": "Aucun article publié pour le moment.", "blog.read_more": "Lire Plus", "blog.contact_us": "Contactez-nous",
    "blog.stay_updated": "Restez Informé", "blog.stay_updated_desc": "Recevez les dernières mises à jour.", "blog.subscribe": "S'abonner",
    "portfolio.badge": "Notre Portfolio", "portfolio.title": "Études de Cas et", "portfolio.title_highlight": "Succès",
    "portfolio.subtitle": "Explorez nos projets réalisés.", "portfolio.loading": "Chargement...",
    "portfolio.coming_soon": "Portfolio bientôt disponible!", "portfolio.discuss_project": "Discutez de votre Projet",
    "portfolio.preview": "Aperçu", "portfolio.view_case_study": "Voir l'Étude", "portfolio.get_quote": "Obtenir un Devis",
    "portfolio.cta_title": "Un Projet en Tête?", "portfolio.cta_desc": "Discutons de comment réaliser votre vision.",
    "portfolio.cta_start": "Démarrer Votre Projet",
    "demo.badge": "Vitrine Projets", "demo.title": "Explorez Notre", "demo.title_highlight": "Vitrine de Projets",
    "demo.subtitle": "Découvrez notre portfolio de projets réussis.",
    "demo.search_placeholder": "Rechercher des projets...", "demo.all": "Tous", "demo.featured": "En Vedette",
    "demo.no_demos": "Projets à Venir", "demo.loading": "Chargement...",
    "demo.view_demo": "Voir la Démo", "demo.quote": "Devis", "demo.views": "vues",
    "demo.no_match": "Aucun Résultat", "demo.no_match_desc": "Ajustez votre recherche.",
    "demo.clear_search": "Effacer la Recherche", "demo.request_demo": "Demander une Démo",
    "demo.custom_title": "Besoin d'une Solution Sur Mesure?", "demo.custom_desc": "Planifiez une consultation personnalisée.",
    "demo.schedule": "Planifier une Consultation", "demo.chat_whatsapp": "Discuter sur WhatsApp",
    "privacy.title": "Politique de Confidentialité", "privacy.back": "Retour à l'Accueil", "terms.title": "Conditions d'Utilisation", "terms.back": "Retour à l'Accueil",
  },
  de: {
    "nav.home": "Startseite", "nav.about": "Über uns", "nav.services": "Leistungen", "nav.portfolio": "Portfolio", "nav.demo": "Demo", "nav.blog": "Blog", "nav.contact": "Kontakt",
    "cta.get_started": "Loslegen",
    "footer.services": "Leistungen", "footer.company": "Unternehmen", "footer.contact": "Kontakt", "footer.rights": "Alle Rechte vorbehalten.", "footer.made_with": "Erstellt mit",
    "footer.enterprise_solutions": "Unternehmenslösungen", "footer.custom_development": "Individuelle Entwicklung", "footer.security_finance": "Sicherheit & Finanzen", "footer.ai_integration": "KI-Integration",
    "footer.about_us": "Über Uns", "footer.privacy": "Datenschutzrichtlinie", "footer.terms": "Nutzungsbedingungen",
    "hero.badge": "Innovation von Morgen, Heute", "hero.title1": "Transformieren Sie Ihr", "hero.title2": "Unternehmen", "hero.title2_suffix": "mit", "hero.title3": "Modernster Technologie",
    "hero.subtitle": "Wir liefern innovative Softwarelösungen, KI-Systeme und IT-Beratung.",
    "hero.cta_project": "Projekt Starten", "hero.cta_demo": "Demos Ansehen",
    "hero.stat_projects": "Projekte Geliefert", "hero.stat_satisfaction": "Kundenzufriedenheit", "hero.stat_experts": "Experten",
    "hero.scroll": "Scrollen", "hero.tag_software": "Softwareentwicklung", "hero.tag_ai": "KI-Lösungen", "hero.tag_consulting": "IT-Beratung", "hero.tag_cloud": "Cloud-Services",
    "services.badge": "Unsere Leistungen", "services.title": "Was Wir", "services.title_highlight": "Anbieten", "services.subtitle": "Umfassende Technologielösungen für Ihr Geschäftswachstum.",
    "services.chat_now": "Jetzt Chatten", "services.view_all": "Alle Leistungen",
    "services.enterprise": "Unternehmenslösungen", "services.enterprise_desc": "Umfassende Geschäftsmanagementsysteme für Ihr Unternehmen.",
    "services.custom": "Individuelle Entwicklung", "services.custom_desc": "Maßgeschneiderte Softwarelösungen für Ihre Anforderungen.",
    "services.security": "Sicherheit & Finanzen", "services.security_desc": "Sichere Finanzsysteme und Compliance-Lösungen.",
    "services.ai": "KI-Integration", "services.ai_desc": "Nutzen Sie KI zur Automatisierung und Optimierung Ihres Unternehmens.",
    "contact.badge": "Kontaktieren Sie uns", "contact.title": "Lassen Sie uns", "contact.title_highlight": "Etwas Großes bauen",
    "contact.subtitle": "Bereit, Ihr Unternehmen mit modernster Technologie zu transformieren?",
    "contact.email_us": "E-Mail", "contact.whatsapp": "WhatsApp", "contact.location": "Standort",
    "contact.form_title": "Nachricht senden", "contact.form_subtitle": "Wir antworten innerhalb von 24h",
    "contact.name": "Ihr Name", "contact.email": "E-Mail-Adresse", "contact.phone": "Telefonnummer", "contact.subject": "Betreff",
    "contact.message": "Ihre Nachricht", "contact.message_placeholder": "Erzählen Sie uns von Ihrem Projekt...",
    "contact.send": "Nachricht senden", "contact.sending": "Wird gesendet...",
    "contact.success_title": "Nachricht gesendet!", "contact.success_desc": "Wir melden uns schnellstmöglich.",
    "contact.error": "Senden fehlgeschlagen. Bitte erneut versuchen.", "contact.characters": "Zeichen",
    "contact.page_badge": "Kontakt", "contact.page_title": "Starten wir ein", "contact.page_title_highlight": "Gespräch",
    "contact.page_subtitle": "Ein Projekt im Sinn? Wir freuen uns auf Ihre Nachricht.",
    "contact.visit_us": "Besuchen Sie uns", "contact.business_hours": "Öffnungszeiten", "contact.hours_value": "So - Do: 9 - 18 Uhr", "contact.call_us": "Rufen Sie an",
    "about.badge": "Über Uns", "about.title": "Die Zukunft der", "about.title_highlight": "Technologie bauen", "about.subtitle": "engineersTech ist ein führendes Softwareunternehmen in Bangladesch.",
    "about.mission_badge": "Unsere Mission", "about.mission_title": "Unternehmen durch Technologie stärken",
    "about.mission_desc": "Bei engineersTech glauben wir an die transformative Kraft der Technologie.",
    "about.mission_1": "Individuelle Software für Ihre Bedürfnisse", "about.mission_2": "Skalierbare Lösungen die mitwachsen",
    "about.mission_3": "24/7 Support und Wartung", "about.mission_4": "Agile Entwicklung für schnellere Lieferung",
    "about.values_badge": "Unsere Werte", "about.values_title": "Was Uns Antreibt",
    "about.value_innovation": "Innovation Zuerst", "about.value_innovation_desc": "Wir verschieben ständig die Grenzen der Technologie.",
    "about.value_client": "Kundenorientiert", "about.value_client_desc": "Ihr Erfolg hat Priorität.",
    "about.value_excellence": "Exzellenz", "about.value_excellence_desc": "Höchste Qualitätsstandards in jedem Projekt.",
    "about.value_integrity": "Integrität", "about.value_integrity_desc": "Transparenz und Ehrlichkeit bilden unser Fundament.",
    "about.team_badge": "Unser Team", "about.team_title": "Die Experten Kennenlernen",
    "about.cta_title": "Bereit mit uns zu Arbeiten?", "about.cta_desc": "Besprechen wir, wie wir Ihr Unternehmen transformieren können.",
    "about.cta_button": "Kontaktieren", "about.cta_services": "Unsere Leistungen",
    "about.stat_projects": "Projekte Abgeschlossen", "about.stat_clients": "Zufriedene Kunden", "about.stat_years": "Jahre Erfahrung", "about.stat_support": "Support Verfügbar",
    "services.page_badge": "Unsere Leistungen", "services.page_title": "Unternehmenslösungen für", "services.page_title_highlight": "Moderne Unternehmen",
    "services.page_subtitle": "Von Softwareentwicklung bis KI-Integration.", "services.free_consultation": "Kostenlose Beratung",
    "services.discuss_whatsapp": "Auf WhatsApp Besprechen", "services.learn_more": "Mehr Erfahren",
    "services.cta_title": "Bereit Ihr Unternehmen zu Transformieren?", "services.cta_desc": "Besprechen wir, wie unsere Lösungen helfen können.",
    "services.cta_start": "Projekt Starten", "services.cta_view_work": "Unsere Arbeit Sehen",
    "services.feat_hrm": "HRM-System", "services.feat_hrm_desc": "Umfassendes Personalmanagement mit Gehaltsabrechnung und Tracking.",
    "services.feat_crm": "CRM-System", "services.feat_crm_desc": "Kundenbeziehungsmanagement für bessere Verkäufe.",
    "services.feat_erp": "ERP-System", "services.feat_erp_desc": "Unternehmensressourcenplanung für reibungslose Abläufe.",
    "services.feat_web": "Webanwendungen", "services.feat_web_desc": "Moderne Webanwendungen mit neuesten Technologien.",
    "services.feat_mobile": "Mobile Apps", "services.feat_mobile_desc": "Native und plattformübergreifende mobile Anwendungen.",
    "services.feat_api": "API-Entwicklung", "services.feat_api_desc": "Robuste APIs für nahtlose Integration.",
    "services.feat_payment": "Zahlungssysteme", "services.feat_payment_desc": "Sichere Zahlungsgateways und Finanztools.",
    "services.feat_banking": "Banklösungen", "services.feat_banking_desc": "Kernbankensysteme und Mobile-Banking-Apps.",
    "services.feat_compliance": "Compliance-Tools", "services.feat_compliance_desc": "Regulatorisches Compliance-Management und Audit.",
    "services.feat_ml": "Machine Learning", "services.feat_ml_desc": "Individuelle ML-Modelle für prädiktive Analysen.",
    "services.feat_analytics": "Datenanalyse", "services.feat_analytics_desc": "KI-gestützte Business Intelligence und Dashboards.",
    "services.feat_chatbot": "Chatbots & NLP", "services.feat_chatbot_desc": "Intelligente Chatbots und Sprachverarbeitung.",
    "blog.badge": "Unser Blog", "blog.title": "Einblicke &", "blog.title_highlight": "Updates",
    "blog.subtitle": "Bleiben Sie informiert über Technologietrends.", "blog.loading": "Wird geladen...",
    "blog.no_posts": "Noch keine Beiträge veröffentlicht.", "blog.read_more": "Mehr Lesen", "blog.contact_us": "Kontaktieren",
    "blog.stay_updated": "Informiert Bleiben", "blog.stay_updated_desc": "Updates zu neuen Beiträgen erhalten.", "blog.subscribe": "Abonnieren",
    "portfolio.badge": "Unser Portfolio", "portfolio.title": "Fallstudien &", "portfolio.title_highlight": "Erfolgsgeschichten",
    "portfolio.subtitle": "Entdecken Sie unsere abgeschlossenen Projekte.", "portfolio.loading": "Wird geladen...",
    "portfolio.coming_soon": "Portfolio kommt bald!", "portfolio.discuss_project": "Projekt Besprechen",
    "portfolio.preview": "Vorschau", "portfolio.view_case_study": "Fallstudie Ansehen", "portfolio.get_quote": "Angebot Erhalten",
    "portfolio.cta_title": "Ein Projekt im Sinn?", "portfolio.cta_desc": "Besprechen wir Ihre Vision.",
    "portfolio.cta_start": "Projekt Starten",
    "demo.badge": "Projektschaufenster", "demo.title": "Entdecken Sie Unser", "demo.title_highlight": "Projektschaufenster",
    "demo.subtitle": "Entdecken Sie unser Portfolio erfolgreicher Projekte.",
    "demo.search_placeholder": "Projekte suchen...", "demo.all": "Alle", "demo.featured": "Empfohlen",
    "demo.no_demos": "Projekte Kommen Bald", "demo.loading": "Wird geladen...",
    "demo.view_demo": "Demo Ansehen", "demo.quote": "Angebot", "demo.views": "Aufrufe",
    "demo.no_match": "Keine Treffer", "demo.no_match_desc": "Passen Sie Ihre Suche an.",
    "demo.clear_search": "Suche Löschen", "demo.request_demo": "Demo Anfragen",
    "demo.custom_title": "Individuelle Lösung Gewünscht?", "demo.custom_desc": "Planen Sie eine persönliche Beratung.",
    "demo.schedule": "Beratung Planen", "demo.chat_whatsapp": "Auf WhatsApp Chatten",
    "privacy.title": "Datenschutzrichtlinie", "privacy.back": "Zurück zur Startseite", "terms.title": "Nutzungsbedingungen", "terms.back": "Zurück zur Startseite",
  },
  zh: {
    "nav.home": "首页", "nav.about": "关于我们", "nav.services": "服务", "nav.portfolio": "案例", "nav.demo": "演示", "nav.blog": "博客", "nav.contact": "联系",
    "cta.get_started": "开始",
    "footer.services": "服务", "footer.company": "公司", "footer.contact": "联系", "footer.rights": "版权所有。", "footer.made_with": "制作",
    "footer.enterprise_solutions": "企业解决方案", "footer.custom_development": "定制开发", "footer.security_finance": "安全与金融", "footer.ai_integration": "AI集成",
    "footer.about_us": "关于我们", "footer.privacy": "隐私政策", "footer.terms": "服务条款",
    "hero.badge": "今天创新明天", "hero.title1": "用", "hero.title2": "前沿科技", "hero.title2_suffix": "转型", "hero.title3": "您的业务",
    "hero.subtitle": "我们提供创新软件解决方案、AI系统和专业IT咨询，帮助企业在数字时代蓬勃发展。",
    "hero.cta_project": "开始您的项目", "hero.cta_demo": "查看演示",
    "hero.stat_projects": "交付项目", "hero.stat_satisfaction": "客户满意度", "hero.stat_experts": "专家团队",
    "hero.scroll": "滚动", "hero.tag_software": "软件开发", "hero.tag_ai": "AI解决方案", "hero.tag_consulting": "IT咨询", "hero.tag_cloud": "云服务",
    "services.badge": "我们的服务", "services.title": "我们", "services.title_highlight": "提供什么", "services.subtitle": "全面的技术解决方案，加速您的业务增长和数字化转型。",
    "services.chat_now": "立即聊天", "services.view_all": "查看所有服务",
    "services.enterprise": "企业解决方案", "services.enterprise_desc": "为您的组织量身定制的综合业务管理系统。",
    "services.custom": "定制开发", "services.custom_desc": "匹配您独特业务需求的定制软件解决方案。",
    "services.security": "安全与金融", "services.security_desc": "安全的金融系统和合规安全解决方案。",
    "services.ai": "AI集成", "services.ai_desc": "利用人工智能自动化和优化您的业务。",
    "contact.badge": "联系我们", "contact.title": "让我们一起", "contact.title_highlight": "创造伟大",
    "contact.subtitle": "准备好用前沿技术转型您的业务了吗？",
    "contact.email_us": "发邮件", "contact.whatsapp": "WhatsApp", "contact.location": "地址",
    "contact.form_title": "给我们留言", "contact.form_subtitle": "我们将在24小时内回复",
    "contact.name": "您的姓名", "contact.email": "邮箱地址", "contact.phone": "电话号码", "contact.subject": "主题",
    "contact.message": "您的留言", "contact.message_placeholder": "告诉我们您的项目...",
    "contact.send": "发送消息", "contact.sending": "发送中...",
    "contact.success_title": "消息已发送！", "contact.success_desc": "我们会尽快回复您。",
    "contact.error": "发送失败，请重试。", "contact.characters": "字符",
    "contact.page_badge": "联系我们", "contact.page_title": "开始一段", "contact.page_title_highlight": "对话",
    "contact.page_subtitle": "有项目想法？我们很乐意听取您的意见。",
    "contact.visit_us": "访问我们", "contact.business_hours": "工作时间", "contact.hours_value": "周日 - 周四: 9AM - 6PM", "contact.call_us": "致电我们",
    "about.badge": "关于我们", "about.title": "构建技术的", "about.title_highlight": "未来", "about.subtitle": "engineersTech是一家位于孟加拉国的领先软件开发公司。",
    "about.mission_badge": "我们的使命", "about.mission_title": "通过技术赋能企业",
    "about.mission_desc": "在engineersTech，我们相信技术的变革力量。",
    "about.mission_1": "为您的需求量身定制软件", "about.mission_2": "随业务增长的可扩展解决方案",
    "about.mission_3": "全天候专属支持与维护", "about.mission_4": "敏捷开发方法快速交付",
    "about.values_badge": "我们的价值观", "about.values_title": "驱动我们前进",
    "about.value_innovation": "创新优先", "about.value_innovation_desc": "我们不断突破技术边界。",
    "about.value_client": "以客户为中心", "about.value_client_desc": "您的成功是我们的优先事项。",
    "about.value_excellence": "卓越", "about.value_excellence_desc": "每个项目保持最高质量标准。",
    "about.value_integrity": "诚信", "about.value_integrity_desc": "透明和诚实是我们业务关系的基础。",
    "about.team_badge": "我们的团队", "about.team_title": "认识专家",
    "about.cta_title": "准备与我们合作？", "about.cta_desc": "讨论如何用我们的技术方案转型您的业务。",
    "about.cta_button": "联系我们", "about.cta_services": "我们的服务",
    "about.stat_projects": "完成项目", "about.stat_clients": "满意客户", "about.stat_years": "年经验", "about.stat_support": "全天候支持",
    "services.page_badge": "我们的服务", "services.page_title": "面向现代企业的", "services.page_title_highlight": "企业解决方案",
    "services.page_subtitle": "从定制软件到AI集成的全面技术解决方案。", "services.free_consultation": "免费咨询",
    "services.discuss_whatsapp": "在WhatsApp上讨论", "services.learn_more": "了解更多",
    "services.cta_title": "准备好转型您的业务？", "services.cta_desc": "讨论我们的解决方案如何帮助您。",
    "services.cta_start": "开始您的项目", "services.cta_view_work": "查看我们的作品",
    "services.feat_hrm": "HRM系统", "services.feat_hrm_desc": "包含薪资、考勤和绩效跟踪的完整人力资源管理。",
    "services.feat_crm": "CRM系统", "services.feat_crm_desc": "提升销售和客户留存的客户关系管理。",
    "services.feat_erp": "ERP系统", "services.feat_erp_desc": "跨部门无缝运营的企业资源规划。",
    "services.feat_web": "Web应用", "services.feat_web_desc": "使用前沿技术的现代响应式Web应用。",
    "services.feat_mobile": "移动应用", "services.feat_mobile_desc": "iOS和Android的原生及跨平台移动应用。",
    "services.feat_api": "API开发", "services.feat_api_desc": "与现有系统无缝集成的强大API。",
    "services.feat_payment": "支付系统", "services.feat_payment_desc": "安全的支付网关和金融管理工具。",
    "services.feat_banking": "银行解决方案", "services.feat_banking_desc": "核心银行系统和移动银行应用。",
    "services.feat_compliance": "合规工具", "services.feat_compliance_desc": "监管合规管理和审计追踪系统。",
    "services.feat_ml": "机器学习", "services.feat_ml_desc": "用于预测分析和自动化的定制ML模型。",
    "services.feat_analytics": "数据分析", "services.feat_analytics_desc": "AI驱动的商业智能和报告仪表板。",
    "services.feat_chatbot": "聊天机器人与NLP", "services.feat_chatbot_desc": "智能聊天机器人和自然语言处理解决方案。",
    "blog.badge": "我们的博客", "blog.title": "洞察与", "blog.title_highlight": "更新",
    "blog.subtitle": "了解技术和数字化转型的最新趋势。", "blog.loading": "加载中...",
    "blog.no_posts": "暂无博客文章。", "blog.read_more": "阅读更多", "blog.contact_us": "联系我们",
    "blog.stay_updated": "保持更新", "blog.stay_updated_desc": "想接收新文章和技术洞察的更新？", "blog.subscribe": "订阅更新",
    "portfolio.badge": "我们的作品", "portfolio.title": "案例研究与", "portfolio.title_highlight": "成功故事",
    "portfolio.subtitle": "探索我们完成的项目。", "portfolio.loading": "加载中...",
    "portfolio.coming_soon": "作品集即将推出！", "portfolio.discuss_project": "讨论您的项目",
    "portfolio.preview": "预览", "portfolio.view_case_study": "查看案例", "portfolio.get_quote": "获取报价",
    "portfolio.cta_title": "有项目想法？", "portfolio.cta_desc": "讨论如何实现您的愿景。",
    "portfolio.cta_start": "开始您的项目",
    "demo.badge": "项目展示", "demo.title": "探索我们的", "demo.title_highlight": "项目展示",
    "demo.subtitle": "发现我们成功项目的作品集。",
    "demo.search_placeholder": "搜索项目...", "demo.all": "全部", "demo.featured": "精选",
    "demo.no_demos": "项目即将推出", "demo.loading": "加载中...",
    "demo.view_demo": "查看演示", "demo.quote": "报价", "demo.views": "浏览",
    "demo.no_match": "未找到匹配项目", "demo.no_match_desc": "调整您的搜索。",
    "demo.clear_search": "清除搜索", "demo.request_demo": "申请演示",
    "demo.custom_title": "需要定制解决方案？", "demo.custom_desc": "安排个性化咨询。",
    "demo.schedule": "预约咨询", "demo.chat_whatsapp": "WhatsApp聊天",
    "privacy.title": "隐私政策", "privacy.back": "返回首页", "terms.title": "服务条款", "terms.back": "返回首页",
  },
  ja: {
    "nav.home": "ホーム", "nav.about": "会社概要", "nav.services": "サービス", "nav.portfolio": "実績", "nav.demo": "デモ", "nav.blog": "ブログ", "nav.contact": "お問い合わせ",
    "cta.get_started": "始める",
    "footer.services": "サービス", "footer.company": "会社", "footer.contact": "お問い合わせ", "footer.rights": "全著作権所有。", "footer.made_with": "作成",
    "footer.enterprise_solutions": "エンタープライズソリューション", "footer.custom_development": "カスタム開発", "footer.security_finance": "セキュリティ＆金融", "footer.ai_integration": "AI統合",
    "footer.about_us": "会社概要", "footer.privacy": "プライバシーポリシー", "footer.terms": "利用規約",
    "hero.badge": "明日のイノベーションを今日に", "hero.title1": "ビジネスを", "hero.title2": "変革", "hero.title2_suffix": "する", "hero.title3": "最先端テクノロジーで",
    "hero.subtitle": "革新的なソフトウェアソリューション、AIシステム、専門ITコンサルティングを提供します。",
    "hero.cta_project": "プロジェクトを開始", "hero.cta_demo": "デモを見る",
    "hero.stat_projects": "納品プロジェクト", "hero.stat_satisfaction": "顧客満足度", "hero.stat_experts": "専門家チーム",
    "hero.scroll": "スクロール", "hero.tag_software": "ソフトウェア開発", "hero.tag_ai": "AIソリューション", "hero.tag_consulting": "ITコンサルティング", "hero.tag_cloud": "クラウドサービス",
    "services.badge": "サービス", "services.title": "私たちの", "services.title_highlight": "提供内容", "services.subtitle": "ビジネス成長を加速する包括的なテクノロジーソリューション。",
    "services.chat_now": "チャット", "services.view_all": "全サービスを見る",
    "services.enterprise": "エンタープライズソリューション", "services.enterprise_desc": "組織に合わせた総合ビジネス管理システム。",
    "services.custom": "カスタム開発", "services.custom_desc": "独自のビジネス要件に合わせたソフトウェアソリューション。",
    "services.security": "セキュリティ＆金融", "services.security_desc": "安全な金融システムとコンプライアンス対応ソリューション。",
    "services.ai": "AI統合", "services.ai_desc": "AIを活用してビジネスを自動化・最適化。",
    "contact.badge": "お問い合わせ", "contact.title": "一緒に", "contact.title_highlight": "素晴らしいものを",
    "contact.subtitle": "最先端技術でビジネスを変革する準備はできていますか？",
    "contact.email_us": "メール", "contact.whatsapp": "WhatsApp", "contact.location": "所在地",
    "contact.form_title": "メッセージを送る", "contact.form_subtitle": "24時間以内に返信します",
    "contact.name": "お名前", "contact.email": "メールアドレス", "contact.phone": "電話番号", "contact.subject": "件名",
    "contact.message": "メッセージ", "contact.message_placeholder": "プロジェクトについて教えてください...",
    "contact.send": "送信", "contact.sending": "送信中...",
    "contact.success_title": "送信完了！", "contact.success_desc": "早急にご連絡いたします。",
    "contact.error": "送信に失敗しました。再試行してください。", "contact.characters": "文字",
    "contact.page_badge": "お問い合わせ", "contact.page_title": "会話を", "contact.page_title_highlight": "始めましょう",
    "contact.page_subtitle": "プロジェクトをお持ちですか？ぜひお聞かせください。",
    "contact.visit_us": "訪問", "contact.business_hours": "営業時間", "contact.hours_value": "日〜木: 9時〜18時", "contact.call_us": "電話",
    "about.badge": "会社概要", "about.title": "テクノロジーの", "about.title_highlight": "未来を構築", "about.subtitle": "engineersTechはバングラデシュの大手ソフトウェア開発会社です。",
    "about.mission_badge": "ミッション", "about.mission_title": "テクノロジーで企業を支援",
    "about.mission_desc": "engineersTechではテクノロジーの変革力を信じています。",
    "about.mission_1": "お客様のニーズに合わせたカスタムソフトウェア", "about.mission_2": "ビジネスと共に成長するスケーラブルなソリューション",
    "about.mission_3": "24時間365日の専任サポート", "about.mission_4": "アジャイル開発で迅速な納品",
    "about.values_badge": "価値観", "about.values_title": "私たちの原動力",
    "about.value_innovation": "イノベーション第一", "about.value_innovation_desc": "常にテクノロジーの限界を押し広げます。",
    "about.value_client": "顧客中心", "about.value_client_desc": "お客様の成功が最優先です。",
    "about.value_excellence": "卓越性", "about.value_excellence_desc": "すべてのプロジェクトで最高品質を維持。",
    "about.value_integrity": "誠実さ", "about.value_integrity_desc": "透明性と誠実さがビジネス関係の基盤。",
    "about.team_badge": "チーム", "about.team_title": "専門家紹介",
    "about.cta_title": "一緒に仕事しませんか？", "about.cta_desc": "テクノロジーソリューションでビジネスを変革する方法を話し合いましょう。",
    "about.cta_button": "お問い合わせ", "about.cta_services": "サービス一覧",
    "about.stat_projects": "完了プロジェクト", "about.stat_clients": "満足顧客", "about.stat_years": "年の経験", "about.stat_support": "サポート対応",
    "services.page_badge": "サービス", "services.page_title": "現代ビジネスのための", "services.page_title_highlight": "エンタープライズソリューション",
    "services.page_subtitle": "カスタム開発からAI統合まで。", "services.free_consultation": "無料相談",
    "services.discuss_whatsapp": "WhatsAppで相談", "services.learn_more": "詳細を見る",
    "services.cta_title": "ビジネス変革の準備はできていますか？", "services.cta_desc": "ソリューションについてご相談ください。",
    "services.cta_start": "プロジェクト開始", "services.cta_view_work": "実績を見る",
    "services.feat_hrm": "HRMシステム", "services.feat_hrm_desc": "給与・勤怠・休暇管理を含む完全な人事管理。",
    "services.feat_crm": "CRMシステム", "services.feat_crm_desc": "売上向上と顧客維持のための顧客関係管理。",
    "services.feat_erp": "ERPシステム", "services.feat_erp_desc": "全部門の業務をシームレスにするリソースプランニング。",
    "services.feat_web": "Webアプリケーション", "services.feat_web_desc": "最新技術を使ったモダンなWebアプリ。",
    "services.feat_mobile": "モバイルアプリ", "services.feat_mobile_desc": "iOS・Androidのネイティブ・クロスプラットフォームアプリ。",
    "services.feat_api": "API開発", "services.feat_api_desc": "既存システムとのシームレスな統合API。",
    "services.feat_payment": "決済システム", "services.feat_payment_desc": "安全な決済ゲートウェイと金融管理ツール。",
    "services.feat_banking": "バンキングソリューション", "services.feat_banking_desc": "コアバンキングとモバイルバンキングアプリ。",
    "services.feat_compliance": "コンプライアンスツール", "services.feat_compliance_desc": "規制準拠管理と監査トレイルシステム。",
    "services.feat_ml": "機械学習", "services.feat_ml_desc": "予測分析と自動化のためのカスタムMLモデル。",
    "services.feat_analytics": "データ分析", "services.feat_analytics_desc": "AI駆動のBIとレポートダッシュボード。",
    "services.feat_chatbot": "チャットボット＆NLP", "services.feat_chatbot_desc": "インテリジェントチャットボットと自然言語処理。",
    "blog.badge": "ブログ", "blog.title": "インサイト＆", "blog.title_highlight": "アップデート",
    "blog.subtitle": "テクノロジーの最新トレンドをチェック。", "blog.loading": "読み込み中...",
    "blog.no_posts": "まだ記事がありません。", "blog.read_more": "続きを読む", "blog.contact_us": "お問い合わせ",
    "blog.stay_updated": "最新情報を入手", "blog.stay_updated_desc": "新しい記事の更新を受け取りませんか？", "blog.subscribe": "購読する",
    "portfolio.badge": "実績", "portfolio.title": "事例紹介＆", "portfolio.title_highlight": "成功事例",
    "portfolio.subtitle": "完了プロジェクトをご覧ください。", "portfolio.loading": "読み込み中...",
    "portfolio.coming_soon": "ポートフォリオ準備中！", "portfolio.discuss_project": "プロジェクトを相談",
    "portfolio.preview": "プレビュー", "portfolio.view_case_study": "事例を見る", "portfolio.get_quote": "見積もり取得",
    "portfolio.cta_title": "プロジェクトをお持ちですか？", "portfolio.cta_desc": "ビジョンの実現をお手伝いします。",
    "portfolio.cta_start": "プロジェクト開始",
    "demo.badge": "プロジェクトショーケース", "demo.title": "探索する", "demo.title_highlight": "プロジェクトショーケース",
    "demo.subtitle": "成功プロジェクトのポートフォリオをご覧ください。",
    "demo.search_placeholder": "プロジェクトを検索...", "demo.all": "すべて", "demo.featured": "注目",
    "demo.no_demos": "プロジェクト準備中", "demo.loading": "読み込み中...",
    "demo.view_demo": "デモを見る", "demo.quote": "見積もり", "demo.views": "閲覧",
    "demo.no_match": "一致するプロジェクトなし", "demo.no_match_desc": "検索を調整してください。",
    "demo.clear_search": "検索をクリア", "demo.request_demo": "デモをリクエスト",
    "demo.custom_title": "カスタムソリューションをお探しですか？", "demo.custom_desc": "個別相談をスケジュールします。",
    "demo.schedule": "相談を予約", "demo.chat_whatsapp": "WhatsAppでチャット",
    "privacy.title": "プライバシーポリシー", "privacy.back": "ホームに戻る", "terms.title": "利用規約", "terms.back": "ホームに戻る",
  },
  ko: {
    "nav.home": "홈", "nav.about": "소개", "nav.services": "서비스", "nav.portfolio": "포트폴리오", "nav.demo": "데모", "nav.blog": "블로그", "nav.contact": "문의",
    "cta.get_started": "시작하기",
    "footer.services": "서비스", "footer.company": "회사", "footer.contact": "문의", "footer.rights": "모든 권리 보유.", "footer.made_with": "제작",
    "footer.enterprise_solutions": "기업 솔루션", "footer.custom_development": "맞춤 개발", "footer.security_finance": "보안 및 금융", "footer.ai_integration": "AI 통합",
    "footer.about_us": "회사 소개", "footer.privacy": "개인정보 처리방침", "footer.terms": "이용약관",
    "hero.badge": "오늘의 혁신, 내일의 미래", "hero.title1": "비즈니스를", "hero.title2": "혁신", "hero.title2_suffix": "하세요", "hero.title3": "최첨단 기술로",
    "hero.subtitle": "혁신적인 소프트웨어 솔루션, AI 시스템, 전문 IT 컨설팅을 제공합니다.",
    "hero.cta_project": "프로젝트 시작", "hero.cta_demo": "데모 보기",
    "hero.stat_projects": "완료 프로젝트", "hero.stat_satisfaction": "고객 만족도", "hero.stat_experts": "전문가 팀",
    "hero.scroll": "스크롤", "hero.tag_software": "소프트웨어 개발", "hero.tag_ai": "AI 솔루션", "hero.tag_consulting": "IT 컨설팅", "hero.tag_cloud": "클라우드 서비스",
    "services.badge": "서비스", "services.title": "우리가", "services.title_highlight": "제공하는 것", "services.subtitle": "비즈니스 성장을 가속화하는 종합 기술 솔루션.",
    "services.chat_now": "채팅", "services.view_all": "모든 서비스 보기",
    "services.enterprise": "기업 솔루션", "services.enterprise_desc": "조직에 맞춘 종합 비즈니스 관리 시스템.",
    "services.custom": "맞춤 개발", "services.custom_desc": "고유한 비즈니스 요구에 맞는 소프트웨어 솔루션.",
    "services.security": "보안 및 금융", "services.security_desc": "안전한 금융 시스템과 규정 준수 솔루션.",
    "services.ai": "AI 통합", "services.ai_desc": "AI를 활용하여 비즈니스를 자동화하고 최적화.",
    "contact.badge": "문의하기", "contact.title": "함께 만들어요", "contact.title_highlight": "멋진 것을",
    "contact.subtitle": "최첨단 기술로 비즈니스를 혁신할 준비가 되셨나요?",
    "contact.email_us": "이메일", "contact.whatsapp": "WhatsApp", "contact.location": "위치",
    "contact.form_title": "메시지 보내기", "contact.form_subtitle": "24시간 내 답변",
    "contact.name": "이름", "contact.email": "이메일 주소", "contact.phone": "전화번호", "contact.subject": "제목",
    "contact.message": "메시지", "contact.message_placeholder": "프로젝트에 대해 알려주세요...",
    "contact.send": "보내기", "contact.sending": "보내는 중...",
    "contact.success_title": "전송 완료!", "contact.success_desc": "빠른 시일 내에 연락드리겠습니다.",
    "contact.error": "전송 실패. 다시 시도해주세요.", "contact.characters": "자",
    "contact.page_badge": "문의", "contact.page_title": "대화를", "contact.page_title_highlight": "시작합시다",
    "contact.page_subtitle": "프로젝트가 있으신가요? 연락 주세요.",
    "contact.visit_us": "방문", "contact.business_hours": "영업시간", "contact.hours_value": "일~목: 오전9시~오후6시", "contact.call_us": "전화",
    "about.badge": "소개", "about.title": "기술의 미래를", "about.title_highlight": "구축", "about.subtitle": "engineersTech는 방글라데시의 선도적인 소프트웨어 개발 기업입니다.",
    "about.mission_badge": "미션", "about.mission_title": "기술을 통한 비즈니스 역량 강화",
    "about.mission_desc": "engineersTech에서는 기술의 변혁적 힘을 믿습니다.",
    "about.mission_1": "고유한 요구에 맞춘 맞춤 소프트웨어", "about.mission_2": "비즈니스와 함께 성장하는 확장 가능한 솔루션",
    "about.mission_3": "24/7 전담 지원 및 유지보수", "about.mission_4": "빠른 배포를 위한 애자일 개발",
    "about.values_badge": "가치", "about.values_title": "우리를 움직이는 것",
    "about.value_innovation": "혁신 우선", "about.value_innovation_desc": "기술의 한계를 끊임없이 넓혀갑니다.",
    "about.value_client": "고객 중심", "about.value_client_desc": "고객의 성공이 최우선입니다.",
    "about.value_excellence": "우수성", "about.value_excellence_desc": "모든 프로젝트에서 최고의 품질 유지.",
    "about.value_integrity": "성실", "about.value_integrity_desc": "투명성과 정직이 비즈니스 관계의 기반.",
    "about.team_badge": "팀", "about.team_title": "전문가 소개",
    "about.cta_title": "함께 일할 준비가 되셨나요?", "about.cta_desc": "기술 솔루션으로 비즈니스를 혁신하는 방법을 논의합시다.",
    "about.cta_button": "문의하기", "about.cta_services": "서비스 보기",
    "about.stat_projects": "완료 프로젝트", "about.stat_clients": "만족 고객", "about.stat_years": "년 경험", "about.stat_support": "지원 가능",
    "services.page_badge": "서비스", "services.page_title": "현대 비즈니스를 위한", "services.page_title_highlight": "기업 솔루션",
    "services.page_subtitle": "맞춤 개발부터 AI 통합까지.", "services.free_consultation": "무료 상담",
    "services.discuss_whatsapp": "WhatsApp으로 상담", "services.learn_more": "자세히 보기",
    "services.cta_title": "비즈니스 혁신 준비 되셨나요?", "services.cta_desc": "솔루션이 어떻게 도움이 될 수 있는지 논의합시다.",
    "services.cta_start": "프로젝트 시작", "services.cta_view_work": "작품 보기",
    "services.feat_hrm": "HRM 시스템", "services.feat_hrm_desc": "급여, 출석, 휴가 관리를 포함한 완전한 인사 관리.",
    "services.feat_crm": "CRM 시스템", "services.feat_crm_desc": "매출 증대와 고객 유지를 위한 고객 관계 관리.",
    "services.feat_erp": "ERP 시스템", "services.feat_erp_desc": "모든 부서의 원활한 운영을 위한 자원 계획.",
    "services.feat_web": "웹 애플리케이션", "services.feat_web_desc": "최신 기술로 만든 모던 웹 애플리케이션.",
    "services.feat_mobile": "모바일 앱", "services.feat_mobile_desc": "iOS와 Android용 네이티브 및 크로스 플랫폼 앱.",
    "services.feat_api": "API 개발", "services.feat_api_desc": "기존 시스템과의 원활한 통합을 위한 강력한 API.",
    "services.feat_payment": "결제 시스템", "services.feat_payment_desc": "안전한 결제 게이트웨이와 금융 관리 도구.",
    "services.feat_banking": "뱅킹 솔루션", "services.feat_banking_desc": "코어 뱅킹 시스템과 모바일 뱅킹 앱.",
    "services.feat_compliance": "컴플라이언스 도구", "services.feat_compliance_desc": "규제 준수 관리 및 감사 추적 시스템.",
    "services.feat_ml": "머신 러닝", "services.feat_ml_desc": "예측 분석과 자동화를 위한 맞춤 ML 모델.",
    "services.feat_analytics": "데이터 분석", "services.feat_analytics_desc": "AI 기반 비즈니스 인텔리전스와 대시보드.",
    "services.feat_chatbot": "챗봇 & NLP", "services.feat_chatbot_desc": "지능형 챗봇과 자연어 처리 솔루션.",
    "blog.badge": "블로그", "blog.title": "인사이트 &", "blog.title_highlight": "업데이트",
    "blog.subtitle": "기술과 디지털 전환의 최신 트렌드를 확인하세요.", "blog.loading": "로딩 중...",
    "blog.no_posts": "아직 게시물이 없습니다.", "blog.read_more": "더 읽기", "blog.contact_us": "문의하기",
    "blog.stay_updated": "최신 정보 받기", "blog.stay_updated_desc": "새 게시물과 기술 인사이트 업데이트를 받으시겠습니까?", "blog.subscribe": "구독하기",
    "portfolio.badge": "포트폴리오", "portfolio.title": "사례 연구 &", "portfolio.title_highlight": "성공 사례",
    "portfolio.subtitle": "완료된 프로젝트를 살펴보세요.", "portfolio.loading": "로딩 중...",
    "portfolio.coming_soon": "포트폴리오 준비 중!", "portfolio.discuss_project": "프로젝트 상담",
    "portfolio.preview": "미리보기", "portfolio.view_case_study": "사례 보기", "portfolio.get_quote": "견적 받기",
    "portfolio.cta_title": "프로젝트가 있으신가요?", "portfolio.cta_desc": "비전 실현을 도와드리겠습니다.",
    "portfolio.cta_start": "프로젝트 시작",
    "demo.badge": "프로젝트 쇼케이스", "demo.title": "탐색하기", "demo.title_highlight": "프로젝트 쇼케이스",
    "demo.subtitle": "성공 프로젝트 포트폴리오를 발견하세요.",
    "demo.search_placeholder": "프로젝트 검색...", "demo.all": "전체", "demo.featured": "추천",
    "demo.no_demos": "프로젝트 준비 중", "demo.loading": "로딩 중...",
    "demo.view_demo": "데모 보기", "demo.quote": "견적", "demo.views": "조회",
    "demo.no_match": "일치하는 프로젝트 없음", "demo.no_match_desc": "검색을 조정해 주세요.",
    "demo.clear_search": "검색 지우기", "demo.request_demo": "데모 요청",
    "demo.custom_title": "맞춤 솔루션이 필요하신가요?", "demo.custom_desc": "맞춤 상담을 예약하세요.",
    "demo.schedule": "상담 예약", "demo.chat_whatsapp": "WhatsApp 채팅",
    "privacy.title": "개인정보 처리방침", "privacy.back": "홈으로 돌아가기", "terms.title": "이용약관", "terms.back": "홈으로 돌아가기",
  },
};

// Timezone-based language detection
const timezoneToLanguage: Record<string, Language> = {
  "Asia/Dhaka": "bn",
  "Asia/Kolkata": "hi", "Asia/Calcutta": "hi",
  "Asia/Tokyo": "ja",
  "Asia/Seoul": "ko",
  "Asia/Shanghai": "zh", "Asia/Hong_Kong": "zh", "Asia/Taipei": "zh",
  "Asia/Riyadh": "ar", "Asia/Dubai": "ar", "Asia/Baghdad": "ar", "Africa/Cairo": "ar",
  "Europe/Madrid": "es", "America/Mexico_City": "es", "America/Buenos_Aires": "es", "America/Bogota": "es",
  "Europe/Paris": "fr", "Africa/Casablanca": "fr",
  "Europe/Berlin": "de", "Europe/Vienna": "de", "Europe/Zurich": "de",
};

const languageNames: Record<Language, string> = {
  en: "English", bn: "বাংলা", ar: "العربية", hi: "हिन्दी", es: "Español", fr: "Français", de: "Deutsch", zh: "中文", ja: "日本語", ko: "한국어",
};

function detectBrowserLanguage(): Language {
  // 1. Check localStorage first
  const stored = localStorage.getItem("app-language");
  if (stored && stored in translationsMap) return stored as Language;

  // 2. Check browser language settings
  const browserLangs = navigator.languages || [navigator.language];
  for (const lang of browserLangs) {
    const code = lang.split("-")[0].toLowerCase() as Language;
    if (code in translationsMap) return code;
  }

  // 3. Fallback to timezone-based detection
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (tz && timezoneToLanguage[tz]) return timezoneToLanguage[tz];
  } catch {}

  return "en";
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  languages: [],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(detectBrowserLanguage);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = useCallback((key: string): string => {
    return translationsMap[language]?.[key] || translationsMap.en[key] || key;
  }, [language]);

  const languages = Object.entries(languageNames).map(([code, name]) => ({
    code: code as Language,
    name,
    flag: languageFlags[code as Language],
  }));

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
