import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from "react";

export type Language = "en" | "bn" | "ar" | "hi" | "es" | "fr" | "de" | "zh" | "ja" | "ko";

interface Translations {
  [key: string]: string;
}

// Short language codes for compact display
const languageFlags: Record<Language, string> = {
  en: "EN", bn: "বা", ar: "عر", hi: "हि", es: "ES", fr: "FR", de: "DE", zh: "中", ja: "日", ko: "한",
};

const translationsMap: Record<Language, Translations> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.demo": "Demo",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "cta.get_started": "Get Started",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.made_with": "Made with",
    "footer.enterprise_solutions": "Enterprise Solutions",
    "footer.custom_development": "Custom Development",
    "footer.security_finance": "Security & Finance",
    "footer.ai_integration": "AI Integration",
    "footer.about_us": "About Us",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    // Hero
    "hero.badge": "Innovating Tomorrow, Today",
    "hero.title1": "Transform Your",
    "hero.title2": "Business",
    "hero.title2_suffix": "with",
    "hero.title3": "Cutting-Edge Tech",
    "hero.subtitle": "We deliver innovative software solutions, AI-powered systems, and expert IT consulting to help businesses thrive in the digital age.",
    "hero.cta_project": "Start Your Project",
    "hero.cta_demo": "View Live Demos",
    "hero.stat_projects": "Projects Delivered",
    "hero.stat_satisfaction": "Client Satisfaction",
    "hero.stat_experts": "Team Experts",
    "hero.scroll": "Scroll",
    "hero.tag_software": "Software Development",
    "hero.tag_ai": "AI Solutions",
    "hero.tag_consulting": "IT Consulting",
    "hero.tag_cloud": "Cloud Services",
    // Services
    "services.badge": "Our Services",
    "services.title": "What We",
    "services.title_highlight": "Offer",
    "services.subtitle": "Comprehensive technology solutions designed to accelerate your business growth and digital transformation.",
    "services.chat_now": "Chat Now",
    "services.view_all": "View All Services",
    "services.enterprise": "Enterprise Solutions",
    "services.enterprise_desc": "Comprehensive business management systems tailored for your organization.",
    "services.custom": "Custom Development",
    "services.custom_desc": "Bespoke software solutions built to match your unique business requirements.",
    "services.security": "Security & Finance",
    "services.security_desc": "Secure financial systems and compliance-ready security solutions.",
    "services.ai": "AI Integration",
    "services.ai_desc": "Leverage artificial intelligence to automate and optimize your business.",
    // Contact
    "contact.badge": "Get in Touch",
    "contact.title": "Let's Build",
    "contact.title_highlight": "Something Great",
    "contact.subtitle": "Ready to transform your business with cutting-edge technology? Get in touch and let's discuss your project.",
    "contact.email_us": "Email Us",
    "contact.whatsapp": "WhatsApp",
    "contact.location": "Location",
    "contact.form_title": "Send us a message",
    "contact.form_subtitle": "We'll respond within 24 hours",
    "contact.name": "Your Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.subject": "Subject",
    "contact.message": "Your Message",
    "contact.message_placeholder": "Tell us about your project...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.success_title": "Message sent!",
    "contact.success_desc": "We'll get back to you as soon as possible.",
    "contact.error": "Failed to send message. Please try again.",
    "contact.characters": "characters",
    // Contact page
    "contact.page_badge": "Contact Us",
    "contact.page_title": "Let's Start a",
    "contact.page_title_highlight": "Conversation",
    "contact.page_subtitle": "Have a project in mind? We'd love to hear from you. Get in touch and let's create something amazing together.",
    "contact.visit_us": "Visit Us",
    "contact.business_hours": "Business Hours",
    "contact.hours_value": "Sun - Thu: 9AM - 6PM",
    "contact.call_us": "Call Us",
    // About
    "about.badge": "About Us",
    "about.title": "Building the Future of",
    "about.title_highlight": "Technology",
    "about.subtitle": "engineersTech is a leading software development company based in Bangladesh, dedicated to delivering innovative enterprise solutions that transform businesses.",
    "about.mission_badge": "Our Mission",
    "about.mission_title": "Empowering Businesses Through Technology",
    "about.mission_desc": "At engineersTech, we believe in the transformative power of technology. Our mission is to help businesses of all sizes leverage cutting-edge solutions to streamline operations, enhance productivity, and achieve sustainable growth.",
    "about.mission_1": "Custom software tailored to your unique needs",
    "about.mission_2": "Scalable solutions that grow with your business",
    "about.mission_3": "24/7 dedicated support and maintenance",
    "about.mission_4": "Agile development methodology for faster delivery",
    "about.values_badge": "Our Values",
    "about.values_title": "What Drives Us",
    "about.value_innovation": "Innovation First",
    "about.value_innovation_desc": "We constantly push the boundaries of technology to deliver cutting-edge solutions.",
    "about.value_client": "Client-Centric",
    "about.value_client_desc": "Your success is our priority. We work closely with you to understand and meet your needs.",
    "about.value_excellence": "Excellence",
    "about.value_excellence_desc": "We maintain the highest standards of quality in every project we undertake.",
    "about.value_integrity": "Integrity",
    "about.value_integrity_desc": "Transparency and honesty form the foundation of our business relationships.",
    "about.team_badge": "Our Team",
    "about.team_title": "Meet the Experts",
    "about.cta_title": "Ready to Work With Us?",
    "about.cta_desc": "Let's discuss how we can help transform your business with our technology solutions.",
    "about.cta_button": "Get in Touch",
    "about.cta_services": "Our Services",
    "about.stat_projects": "Projects Completed",
    "about.stat_clients": "Happy Clients",
    "about.stat_years": "Years Experience",
    "about.stat_support": "Support Available",
    // Services page
    "services.page_badge": "Our Services",
    "services.page_title": "Enterprise Solutions for",
    "services.page_title_highlight": "Modern Business",
    "services.page_subtitle": "From custom software development to AI integration, we provide comprehensive technology solutions that drive growth and efficiency.",
    "services.free_consultation": "Get a Free Consultation",
    "services.discuss_whatsapp": "Discuss on WhatsApp",
    "services.learn_more": "Learn More",
    "services.cta_title": "Ready to Transform Your Business?",
    "services.cta_desc": "Let's discuss how our solutions can help you achieve your goals.",
    "services.cta_start": "Start Your Project",
    "services.cta_view_work": "View Our Work",
    // Blog
    "blog.badge": "Our Blog",
    "blog.title": "Insights &",
    "blog.title_highlight": "Updates",
    "blog.subtitle": "Stay updated with the latest trends in technology, software development, and digital transformation.",
    "blog.loading": "Loading posts...",
    "blog.no_posts": "No blog posts published yet. Check back soon for updates!",
    "blog.read_more": "Read More",
    "blog.contact_us": "Contact Us",
    "blog.stay_updated": "Stay Updated",
    "blog.stay_updated_desc": "Want to receive updates about new posts and tech insights? Get in touch with us.",
    "blog.subscribe": "Subscribe to Updates",
    // Portfolio
    "portfolio.badge": "Our Portfolio",
    "portfolio.title": "Case Studies &",
    "portfolio.title_highlight": "Success Stories",
    "portfolio.subtitle": "Explore our completed projects and see how we've helped businesses transform through innovative technology solutions.",
    "portfolio.loading": "Loading projects...",
    "portfolio.coming_soon": "Portfolio coming soon! We're documenting our amazing projects.",
    "portfolio.discuss_project": "Discuss Your Project",
    "portfolio.preview": "Preview",
    "portfolio.view_case_study": "View Case Study",
    "portfolio.get_quote": "Get Quote",
    "portfolio.cta_title": "Have a Project in Mind?",
    "portfolio.cta_desc": "Let's discuss how we can help bring your vision to life with our expertise.",
    "portfolio.cta_start": "Start Your Project",
    // Demo
    "demo.badge": "Project Showcase",
    "demo.title": "Explore Our",
    "demo.title_highlight": "Project Showcase",
    "demo.subtitle": "Discover our portfolio of successful projects. Interactive demos, live previews, and detailed case studies.",
    "demo.search_placeholder": "Search projects by name or description...",
    "demo.all": "All Projects",
    "demo.featured": "Featured",
    "demo.no_demos": "Projects Coming Soon",
    "demo.loading": "Loading projects...",
    // Privacy / Terms
    "privacy.title": "Privacy Policy",
    "privacy.back": "Back to Home",
    "terms.title": "Terms of Service",
    "terms.back": "Back to Home",
  },
  bn: {
    "nav.home": "হোম", "nav.about": "আমাদের সম্পর্কে", "nav.services": "সেবাসমূহ", "nav.portfolio": "পোর্টফোলিও", "nav.demo": "ডেমো", "nav.blog": "ব্লগ", "nav.contact": "যোগাযোগ",
    "cta.get_started": "শুরু করুন",
    "footer.services": "সেবাসমূহ", "footer.company": "কোম্পানি", "footer.contact": "যোগাযোগ", "footer.rights": "সর্বস্বত্ব সংরক্ষিত।", "footer.made_with": "তৈরি করা হয়েছে",
    "footer.enterprise_solutions": "এন্টারপ্রাইজ সমাধান", "footer.custom_development": "কাস্টম ডেভেলপমেন্ট", "footer.security_finance": "নিরাপত্তা ও অর্থায়ন", "footer.ai_integration": "এআই ইন্টিগ্রেশন",
    "footer.about_us": "আমাদের সম্পর্কে", "footer.privacy": "গোপনীয়তা নীতি", "footer.terms": "সেবার শর্তাবলী",
    "hero.badge": "আজই আগামীকালের উদ্ভাবন", "hero.title1": "আপনার ব্যবসাকে", "hero.title2": "রূপান্তর", "hero.title2_suffix": "করুন", "hero.title3": "অত্যাধুনিক প্রযুক্তিতে",
    "hero.subtitle": "আমরা উদ্ভাবনী সফটওয়্যার সমাধান, এআই-চালিত সিস্টেম এবং বিশেষজ্ঞ আইটি পরামর্শ প্রদান করি।",
    "hero.cta_project": "আপনার প্রকল্প শুরু করুন", "hero.cta_demo": "লাইভ ডেমো দেখুন",
    "hero.stat_projects": "প্রকল্প সম্পন্ন", "hero.stat_satisfaction": "ক্লায়েন্ট সন্তুষ্টি", "hero.stat_experts": "দলের বিশেষজ্ঞ",
    "hero.scroll": "স্ক্রল", "hero.tag_software": "সফটওয়্যার ডেভেলপমেন্ট", "hero.tag_ai": "এআই সমাধান", "hero.tag_consulting": "আইটি পরামর্শ", "hero.tag_cloud": "ক্লাউড সেবা",
    "services.badge": "আমাদের সেবাসমূহ", "services.title": "আমরা কি", "services.title_highlight": "অফার করি", "services.subtitle": "আপনার ব্যবসার বৃদ্ধি ত্বরান্বিত করতে ব্যাপক প্রযুক্তি সমাধান।",
    "services.chat_now": "চ্যাট করুন", "services.view_all": "সব সেবা দেখুন",
    "services.enterprise": "এন্টারপ্রাইজ সমাধান", "services.enterprise_desc": "আপনার প্রতিষ্ঠানের জন্য তৈরি ব্যাপক ব্যবসা ব্যবস্থাপনা সিস্টেম।",
    "services.custom": "কাস্টম ডেভেলপমেন্ট", "services.custom_desc": "আপনার অনন্য ব্যবসায়িক প্রয়োজনীয়তার সাথে মিলানো সফটওয়্যার সমাধান।",
    "services.security": "নিরাপত্তা ও অর্থায়ন", "services.security_desc": "নিরাপদ আর্থিক সিস্টেম এবং সম্মতি-প্রস্তুত নিরাপত্তা সমাধান।",
    "services.ai": "এআই ইন্টিগ্রেশন", "services.ai_desc": "আপনার ব্যবসা স্বয়ংক্রিয় ও অপ্টিমাইজ করতে কৃত্রিম বুদ্ধিমত্তা।",
    "contact.badge": "যোগাযোগ করুন", "contact.title": "আসুন তৈরি করি", "contact.title_highlight": "অসাধারণ কিছু",
    "contact.subtitle": "অত্যাধুনিক প্রযুক্তিতে আপনার ব্যবসা রূপান্তর করতে প্রস্তুত?",
    "contact.email_us": "ইমেইল করুন", "contact.whatsapp": "হোয়াটসঅ্যাপ", "contact.location": "অবস্থান",
    "contact.form_title": "আমাদের একটি বার্তা পাঠান", "contact.form_subtitle": "আমরা ২৪ ঘন্টার মধ্যে উত্তর দেব",
    "contact.name": "আপনার নাম", "contact.email": "ইমেইল ঠিকানা", "contact.phone": "ফোন নম্বর", "contact.subject": "বিষয়",
    "contact.message": "আপনার বার্তা", "contact.message_placeholder": "আপনার প্রকল্প সম্পর্কে বলুন...",
    "contact.send": "বার্তা পাঠান", "contact.sending": "পাঠানো হচ্ছে...",
    "contact.success_title": "বার্তা পাঠানো হয়েছে!", "contact.success_desc": "আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
    "contact.error": "বার্তা পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।", "contact.characters": "অক্ষর",
    "contact.page_badge": "যোগাযোগ", "contact.page_title": "আসুন শুরু করি একটি", "contact.page_title_highlight": "কথোপকথন",
    "contact.page_subtitle": "একটি প্রকল্প মনে আছে? আমরা আপনার কাছ থেকে শুনতে চাই।",
    "contact.visit_us": "আমাদের দেখুন", "contact.business_hours": "কর্ম সময়", "contact.hours_value": "রবি - বৃহঃ: সকাল ৯ - সন্ধ্যা ৬", "contact.call_us": "কল করুন",
  },
  ar: {
    "nav.home": "الرئيسية", "nav.about": "عن الشركة", "nav.services": "الخدمات", "nav.portfolio": "الأعمال", "nav.demo": "عرض تجريبي", "nav.blog": "المدونة", "nav.contact": "اتصل بنا",
    "cta.get_started": "ابدأ الآن",
    "footer.services": "الخدمات", "footer.company": "الشركة", "footer.contact": "اتصل بنا", "footer.rights": "جميع الحقوق محفوظة.", "footer.made_with": "صنع بـ",
    "footer.enterprise_solutions": "حلول المؤسسات", "footer.custom_development": "تطوير مخصص", "footer.security_finance": "الأمن والتمويل", "footer.ai_integration": "تكامل الذكاء الاصطناعي",
    "footer.about_us": "من نحن", "footer.privacy": "سياسة الخصوصية", "footer.terms": "شروط الخدمة",
    "hero.badge": "ابتكار الغد، اليوم", "hero.title1": "حوّل أعمالك", "hero.title2": "التجارية", "hero.title2_suffix": "مع", "hero.title3": "تكنولوجيا متطورة",
    "hero.subtitle": "نقدم حلول برمجية مبتكرة وأنظمة ذكاء اصطناعي واستشارات تقنية متخصصة.",
    "hero.cta_project": "ابدأ مشروعك", "hero.cta_demo": "شاهد العروض",
    "hero.stat_projects": "مشروع منجز", "hero.stat_satisfaction": "رضا العملاء", "hero.stat_experts": "خبير في الفريق",
    "hero.scroll": "تمرير", "hero.tag_software": "تطوير البرمجيات", "hero.tag_ai": "حلول الذكاء الاصطناعي", "hero.tag_consulting": "استشارات تقنية", "hero.tag_cloud": "خدمات سحابية",
    "services.badge": "خدماتنا", "services.title": "ماذا", "services.title_highlight": "نقدم", "services.subtitle": "حلول تقنية شاملة لتسريع نمو أعمالك والتحول الرقمي.",
    "services.chat_now": "تحدث الآن", "services.view_all": "عرض جميع الخدمات",
    "services.enterprise": "حلول المؤسسات", "services.enterprise_desc": "أنظمة إدارة أعمال شاملة مصممة لمؤسستك.",
    "services.custom": "تطوير مخصص", "services.custom_desc": "حلول برمجية مخصصة لتلبية متطلباتك الفريدة.",
    "services.security": "الأمن والتمويل", "services.security_desc": "أنظمة مالية آمنة وحلول أمان جاهزة للامتثال.",
    "services.ai": "تكامل الذكاء الاصطناعي", "services.ai_desc": "استفد من الذكاء الاصطناعي لأتمتة وتحسين أعمالك.",
    "contact.badge": "تواصل معنا", "contact.title": "لنبني", "contact.title_highlight": "شيئاً رائعاً",
    "contact.subtitle": "مستعد لتحويل عملك بالتكنولوجيا المتطورة؟",
    "contact.email_us": "راسلنا", "contact.whatsapp": "واتساب", "contact.location": "الموقع",
    "contact.form_title": "أرسل لنا رسالة", "contact.form_subtitle": "سنرد خلال 24 ساعة",
    "contact.name": "اسمك", "contact.email": "البريد الإلكتروني", "contact.phone": "رقم الهاتف", "contact.subject": "الموضوع",
    "contact.message": "رسالتك", "contact.message_placeholder": "أخبرنا عن مشروعك...",
    "contact.send": "إرسال الرسالة", "contact.sending": "جارِ الإرسال...",
    "contact.success_title": "تم الإرسال!", "contact.success_desc": "سنتواصل معك في أقرب وقت.",
    "contact.error": "فشل الإرسال. حاول مرة أخرى.", "contact.characters": "حرف",
    "contact.page_badge": "اتصل بنا", "contact.page_title": "لنبدأ", "contact.page_title_highlight": "محادثة",
    "contact.page_subtitle": "لديك مشروع في ذهنك؟ نحب أن نسمع منك.",
    "contact.visit_us": "زرنا", "contact.business_hours": "ساعات العمل", "contact.hours_value": "الأحد - الخميس: 9ص - 6م", "contact.call_us": "اتصل بنا",
  },
  hi: {
    "nav.home": "होम", "nav.about": "हमारे बारे में", "nav.services": "सेवाएं", "nav.portfolio": "पोर्टफोलियो", "nav.demo": "डेमो", "nav.blog": "ब्लॉग", "nav.contact": "संपर्क",
    "cta.get_started": "शुरू करें",
    "footer.services": "सेवाएं", "footer.company": "कंपनी", "footer.contact": "संपर्क", "footer.rights": "सर्वाधिकार सुरक्षित।", "footer.made_with": "बनाया गया",
    "footer.enterprise_solutions": "एंटरप्राइज समाधान", "footer.custom_development": "कस्टम विकास", "footer.security_finance": "सुरक्षा और वित्त", "footer.ai_integration": "एआई एकीकरण",
    "footer.about_us": "हमारे बारे में", "footer.privacy": "गोपनीयता नीति", "footer.terms": "सेवा की शर्तें",
    "hero.badge": "आज ही कल का नवाचार", "hero.title1": "अपने व्यापार को", "hero.title2": "बदलें", "hero.title2_suffix": "के साथ", "hero.title3": "अत्याधुनिक तकनीक",
    "hero.subtitle": "हम नवीन सॉफ्टवेयर समाधान, एआई-संचालित प्रणालियां और विशेषज्ञ आईटी परामर्श प्रदान करते हैं।",
    "hero.cta_project": "अपना प्रोजेक्ट शुरू करें", "hero.cta_demo": "लाइव डेमो देखें",
    "hero.stat_projects": "प्रोजेक्ट पूरे", "hero.stat_satisfaction": "ग्राहक संतुष्टि", "hero.stat_experts": "विशेषज्ञ",
    "hero.scroll": "स्क्रॉल", "hero.tag_software": "सॉफ्टवेयर विकास", "hero.tag_ai": "एआई समाधान", "hero.tag_consulting": "आईटी परामर्श", "hero.tag_cloud": "क्लाउड सेवाएं",
    "services.badge": "हमारी सेवाएं", "services.title": "हम क्या", "services.title_highlight": "प्रदान करते हैं", "services.subtitle": "आपके व्यापार विकास को तेज करने के लिए व्यापक तकनीकी समाधान।",
    "services.chat_now": "चैट करें", "services.view_all": "सभी सेवाएं देखें",
    "services.enterprise": "एंटरप्राइज समाधान", "services.enterprise_desc": "आपके संगठन के लिए तैयार व्यापक व्यवसाय प्रबंधन प्रणालियां।",
    "services.custom": "कस्टम विकास", "services.custom_desc": "आपकी अनूठी व्यावसायिक आवश्यकताओं के अनुरूप सॉफ्टवेयर समाधान।",
    "services.security": "सुरक्षा और वित्त", "services.security_desc": "सुरक्षित वित्तीय प्रणालियां और अनुपालन-तैयार सुरक्षा समाधान।",
    "services.ai": "एआई एकीकरण", "services.ai_desc": "अपने व्यवसाय को स्वचालित और अनुकूलित करने के लिए कृत्रिम बुद्धिमत्ता।",
    "contact.badge": "संपर्क करें", "contact.title": "आइए बनाएं", "contact.title_highlight": "कुछ शानदार",
    "contact.subtitle": "अत्याधुनिक तकनीक से अपने व्यवसाय को बदलने के लिए तैयार?",
    "contact.email_us": "ईमेल करें", "contact.whatsapp": "व्हाट्सएप", "contact.location": "स्थान",
    "contact.form_title": "हमें संदेश भेजें", "contact.form_subtitle": "हम 24 घंटे में जवाब देंगे",
    "contact.name": "आपका नाम", "contact.email": "ईमेल पता", "contact.phone": "फोन नंबर", "contact.subject": "विषय",
    "contact.message": "आपका संदेश", "contact.message_placeholder": "अपने प्रोजेक्ट के बारे में बताएं...",
    "contact.send": "संदेश भेजें", "contact.sending": "भेजा जा रहा है...",
    "contact.success_title": "संदेश भेजा गया!", "contact.success_desc": "हम जल्द ही आपसे संपर्क करेंगे।",
    "contact.error": "संदेश भेजने में विफल। पुनः प्रयास करें।", "contact.characters": "अक्षर",
    "contact.page_badge": "संपर्क", "contact.page_title": "शुरू करें एक", "contact.page_title_highlight": "बातचीत",
    "contact.page_subtitle": "कोई प्रोजेक्ट है? हम आपसे सुनना चाहेंगे।",
    "contact.visit_us": "हमसे मिलें", "contact.business_hours": "कार्य समय", "contact.hours_value": "रवि - गुरु: सुबह 9 - शाम 6", "contact.call_us": "कॉल करें",
  },
  es: {
    "nav.home": "Inicio", "nav.about": "Nosotros", "nav.services": "Servicios", "nav.portfolio": "Portafolio", "nav.demo": "Demo", "nav.blog": "Blog", "nav.contact": "Contacto",
    "cta.get_started": "Empezar",
    "footer.services": "Servicios", "footer.company": "Empresa", "footer.contact": "Contacto", "footer.rights": "Todos los derechos reservados.", "footer.made_with": "Hecho con",
    "footer.enterprise_solutions": "Soluciones Empresariales", "footer.custom_development": "Desarrollo a Medida", "footer.security_finance": "Seguridad y Finanzas", "footer.ai_integration": "Integración de IA",
    "footer.about_us": "Sobre Nosotros", "footer.privacy": "Política de Privacidad", "footer.terms": "Términos de Servicio",
    "hero.badge": "Innovando el Mañana, Hoy", "hero.title1": "Transforma Tu", "hero.title2": "Negocio", "hero.title2_suffix": "con", "hero.title3": "Tecnología de Vanguardia",
    "hero.subtitle": "Ofrecemos soluciones de software innovadoras, sistemas de IA y consultoría TI experta.",
    "hero.cta_project": "Inicia Tu Proyecto", "hero.cta_demo": "Ver Demos",
    "hero.stat_projects": "Proyectos Entregados", "hero.stat_satisfaction": "Satisfacción del Cliente", "hero.stat_experts": "Expertos",
    "hero.scroll": "Desplazar", "hero.tag_software": "Desarrollo de Software", "hero.tag_ai": "Soluciones IA", "hero.tag_consulting": "Consultoría TI", "hero.tag_cloud": "Servicios Cloud",
    "services.badge": "Nuestros Servicios", "services.title": "Qué", "services.title_highlight": "Ofrecemos", "services.subtitle": "Soluciones tecnológicas integrales para acelerar el crecimiento de tu negocio.",
    "services.chat_now": "Chatear", "services.view_all": "Ver Todos los Servicios",
    "services.enterprise": "Soluciones Empresariales", "services.enterprise_desc": "Sistemas integrales de gestión empresarial.",
    "services.custom": "Desarrollo a Medida", "services.custom_desc": "Soluciones de software a medida para tu negocio.",
    "services.security": "Seguridad y Finanzas", "services.security_desc": "Sistemas financieros seguros y soluciones de cumplimiento.",
    "services.ai": "Integración de IA", "services.ai_desc": "Aprovecha la IA para automatizar y optimizar tu negocio.",
    "contact.badge": "Contáctanos", "contact.title": "Construyamos", "contact.title_highlight": "Algo Grandioso",
    "contact.subtitle": "¿Listo para transformar tu negocio con tecnología de vanguardia?",
    "contact.email_us": "Escríbenos", "contact.whatsapp": "WhatsApp", "contact.location": "Ubicación",
    "contact.form_title": "Envíanos un mensaje", "contact.form_subtitle": "Respondemos en 24 horas",
    "contact.name": "Tu Nombre", "contact.email": "Correo Electrónico", "contact.phone": "Teléfono", "contact.subject": "Asunto",
    "contact.message": "Tu Mensaje", "contact.message_placeholder": "Cuéntanos sobre tu proyecto...",
    "contact.send": "Enviar Mensaje", "contact.sending": "Enviando...",
    "contact.success_title": "¡Mensaje enviado!", "contact.success_desc": "Te contactaremos lo antes posible.",
    "contact.error": "Error al enviar. Inténtalo de nuevo.", "contact.characters": "caracteres",
    "contact.page_badge": "Contacto", "contact.page_title": "Iniciemos una", "contact.page_title_highlight": "Conversación",
    "contact.page_subtitle": "¿Tienes un proyecto en mente? Nos encantaría escucharte.",
    "contact.visit_us": "Visítanos", "contact.business_hours": "Horario", "contact.hours_value": "Dom - Jue: 9AM - 6PM", "contact.call_us": "Llámanos",
  },
  fr: {
    "nav.home": "Accueil", "nav.about": "À propos", "nav.services": "Services", "nav.portfolio": "Portfolio", "nav.demo": "Démo", "nav.blog": "Blog", "nav.contact": "Contact",
    "cta.get_started": "Commencer",
    "footer.services": "Services", "footer.company": "Entreprise", "footer.contact": "Contact", "footer.rights": "Tous droits réservés.", "footer.made_with": "Fait avec",
    "footer.enterprise_solutions": "Solutions d'Entreprise", "footer.custom_development": "Développement Sur Mesure", "footer.security_finance": "Sécurité & Finance", "footer.ai_integration": "Intégration IA",
    "footer.about_us": "À Propos", "footer.privacy": "Politique de Confidentialité", "footer.terms": "Conditions d'Utilisation",
    "hero.badge": "Innover Demain, Aujourd'hui", "hero.title1": "Transformez Votre", "hero.title2": "Entreprise", "hero.title2_suffix": "avec", "hero.title3": "Technologie de Pointe",
    "hero.subtitle": "Nous fournissons des solutions logicielles innovantes, des systèmes IA et du conseil IT expert.",
    "hero.cta_project": "Démarrer Votre Projet", "hero.cta_demo": "Voir les Démos",
    "hero.stat_projects": "Projets Livrés", "hero.stat_satisfaction": "Satisfaction Client", "hero.stat_experts": "Experts",
    "hero.scroll": "Défiler", "hero.tag_software": "Développement Logiciel", "hero.tag_ai": "Solutions IA", "hero.tag_consulting": "Conseil IT", "hero.tag_cloud": "Services Cloud",
    "services.badge": "Nos Services", "services.title": "Ce Que Nous", "services.title_highlight": "Offrons", "services.subtitle": "Des solutions technologiques complètes pour accélérer la croissance de votre entreprise.",
    "services.chat_now": "Discuter", "services.view_all": "Voir Tous les Services",
    "services.enterprise": "Solutions d'Entreprise", "services.enterprise_desc": "Systèmes de gestion d'entreprise complets.",
    "services.custom": "Développement Sur Mesure", "services.custom_desc": "Solutions logicielles personnalisées pour votre entreprise.",
    "services.security": "Sécurité & Finance", "services.security_desc": "Systèmes financiers sécurisés et solutions de conformité.",
    "services.ai": "Intégration IA", "services.ai_desc": "Exploitez l'IA pour automatiser et optimiser votre entreprise.",
    "contact.badge": "Contactez-nous", "contact.title": "Construisons", "contact.title_highlight": "Quelque Chose de Grand",
    "contact.subtitle": "Prêt à transformer votre entreprise avec la technologie de pointe?",
    "contact.email_us": "Email", "contact.whatsapp": "WhatsApp", "contact.location": "Emplacement",
    "contact.form_title": "Envoyez-nous un message", "contact.form_subtitle": "Nous répondons sous 24h",
    "contact.name": "Votre Nom", "contact.email": "Adresse Email", "contact.phone": "Téléphone", "contact.subject": "Sujet",
    "contact.message": "Votre Message", "contact.message_placeholder": "Parlez-nous de votre projet...",
    "contact.send": "Envoyer", "contact.sending": "Envoi...",
    "contact.success_title": "Message envoyé!", "contact.success_desc": "Nous vous répondrons rapidement.",
    "contact.error": "Échec de l'envoi. Réessayez.", "contact.characters": "caractères",
    "contact.page_badge": "Contact", "contact.page_title": "Commençons une", "contact.page_title_highlight": "Conversation",
    "contact.page_subtitle": "Un projet en tête? Contactez-nous.",
    "contact.visit_us": "Visitez-nous", "contact.business_hours": "Horaires", "contact.hours_value": "Dim - Jeu: 9h - 18h", "contact.call_us": "Appelez-nous",
  },
  de: {
    "nav.home": "Startseite", "nav.about": "Über uns", "nav.services": "Leistungen", "nav.portfolio": "Portfolio", "nav.demo": "Demo", "nav.blog": "Blog", "nav.contact": "Kontakt",
    "cta.get_started": "Loslegen",
    "footer.services": "Leistungen", "footer.company": "Unternehmen", "footer.contact": "Kontakt", "footer.rights": "Alle Rechte vorbehalten.", "footer.made_with": "Erstellt mit",
    "footer.enterprise_solutions": "Unternehmenslösungen", "footer.custom_development": "Individuelle Entwicklung", "footer.security_finance": "Sicherheit & Finanzen", "footer.ai_integration": "KI-Integration",
    "footer.about_us": "Über Uns", "footer.privacy": "Datenschutzrichtlinie", "footer.terms": "Nutzungsbedingungen",
    "hero.badge": "Innovation von Morgen, Heute", "hero.title1": "Transformieren Sie Ihr", "hero.title2": "Unternehmen", "hero.title2_suffix": "mit", "hero.title3": "Modernster Technologie",
    "hero.subtitle": "Wir liefern innovative Softwarelösungen, KI-Systeme und IT-Beratung.",
    "hero.cta_project": "Projekt Starten", "hero.cta_demo": "Demos Ansehen",
    "hero.stat_projects": "Projekte Geliefert", "hero.stat_satisfaction": "Kundenzufriedenheit", "hero.stat_experts": "Experten",
    "hero.scroll": "Scrollen", "hero.tag_software": "Softwareentwicklung", "hero.tag_ai": "KI-Lösungen", "hero.tag_consulting": "IT-Beratung", "hero.tag_cloud": "Cloud-Services",
    "services.badge": "Unsere Leistungen", "services.title": "Was Wir", "services.title_highlight": "Anbieten", "services.subtitle": "Umfassende Technologielösungen für Ihr Geschäftswachstum.",
    "services.chat_now": "Jetzt Chatten", "services.view_all": "Alle Leistungen",
    "services.enterprise": "Unternehmenslösungen", "services.enterprise_desc": "Umfassende Geschäftsmanagementsysteme für Ihr Unternehmen.",
    "services.custom": "Individuelle Entwicklung", "services.custom_desc": "Maßgeschneiderte Softwarelösungen für Ihre Anforderungen.",
    "services.security": "Sicherheit & Finanzen", "services.security_desc": "Sichere Finanzsysteme und Compliance-Lösungen.",
    "services.ai": "KI-Integration", "services.ai_desc": "Nutzen Sie KI zur Automatisierung und Optimierung Ihres Unternehmens.",
    "contact.badge": "Kontaktieren Sie uns", "contact.title": "Lassen Sie uns", "contact.title_highlight": "Etwas Großes bauen",
    "contact.subtitle": "Bereit, Ihr Unternehmen mit modernster Technologie zu transformieren?",
    "contact.email_us": "E-Mail", "contact.whatsapp": "WhatsApp", "contact.location": "Standort",
    "contact.form_title": "Nachricht senden", "contact.form_subtitle": "Wir antworten innerhalb von 24h",
    "contact.name": "Ihr Name", "contact.email": "E-Mail-Adresse", "contact.phone": "Telefonnummer", "contact.subject": "Betreff",
    "contact.message": "Ihre Nachricht", "contact.message_placeholder": "Erzählen Sie uns von Ihrem Projekt...",
    "contact.send": "Nachricht senden", "contact.sending": "Wird gesendet...",
    "contact.success_title": "Nachricht gesendet!", "contact.success_desc": "Wir melden uns schnellstmöglich.",
    "contact.error": "Senden fehlgeschlagen. Bitte erneut versuchen.", "contact.characters": "Zeichen",
    "contact.page_badge": "Kontakt", "contact.page_title": "Starten wir ein", "contact.page_title_highlight": "Gespräch",
    "contact.page_subtitle": "Ein Projekt im Sinn? Wir freuen uns auf Ihre Nachricht.",
    "contact.visit_us": "Besuchen Sie uns", "contact.business_hours": "Öffnungszeiten", "contact.hours_value": "So - Do: 9 - 18 Uhr", "contact.call_us": "Rufen Sie an",
  },
  zh: {
    "nav.home": "首页", "nav.about": "关于我们", "nav.services": "服务", "nav.portfolio": "案例", "nav.demo": "演示", "nav.blog": "博客", "nav.contact": "联系",
    "cta.get_started": "开始",
    "footer.services": "服务", "footer.company": "公司", "footer.contact": "联系", "footer.rights": "版权所有。", "footer.made_with": "制作",
    "footer.enterprise_solutions": "企业解决方案", "footer.custom_development": "定制开发", "footer.security_finance": "安全与金融", "footer.ai_integration": "AI集成",
    "footer.about_us": "关于我们", "footer.privacy": "隐私政策", "footer.terms": "服务条款",
    "hero.badge": "今天创新明天", "hero.title1": "用", "hero.title2": "前沿科技", "hero.title2_suffix": "转型", "hero.title3": "您的业务",
    "hero.subtitle": "我们提供创新软件解决方案、AI系统和专业IT咨询，帮助企业在数字时代蓬勃发展。",
    "hero.cta_project": "开始您的项目", "hero.cta_demo": "查看演示",
    "hero.stat_projects": "交付项目", "hero.stat_satisfaction": "客户满意度", "hero.stat_experts": "专家团队",
    "hero.scroll": "滚动", "hero.tag_software": "软件开发", "hero.tag_ai": "AI解决方案", "hero.tag_consulting": "IT咨询", "hero.tag_cloud": "云服务",
    "services.badge": "我们的服务", "services.title": "我们", "services.title_highlight": "提供什么", "services.subtitle": "全面的技术解决方案，加速您的业务增长和数字化转型。",
    "services.chat_now": "立即聊天", "services.view_all": "查看所有服务",
    "services.enterprise": "企业解决方案", "services.enterprise_desc": "为您的组织量身定制的综合业务管理系统。",
    "services.custom": "定制开发", "services.custom_desc": "匹配您独特业务需求的定制软件解决方案。",
    "services.security": "安全与金融", "services.security_desc": "安全的金融系统和合规安全解决方案。",
    "services.ai": "AI集成", "services.ai_desc": "利用人工智能自动化和优化您的业务。",
    "contact.badge": "联系我们", "contact.title": "让我们一起", "contact.title_highlight": "创造伟大",
    "contact.subtitle": "准备好用前沿技术转型您的业务了吗？",
    "contact.email_us": "发邮件", "contact.whatsapp": "WhatsApp", "contact.location": "地址",
    "contact.form_title": "给我们留言", "contact.form_subtitle": "我们将在24小时内回复",
    "contact.name": "您的姓名", "contact.email": "邮箱地址", "contact.phone": "电话号码", "contact.subject": "主题",
    "contact.message": "您的留言", "contact.message_placeholder": "告诉我们您的项目...",
    "contact.send": "发送消息", "contact.sending": "发送中...",
    "contact.success_title": "消息已发送！", "contact.success_desc": "我们会尽快回复您。",
    "contact.error": "发送失败，请重试。", "contact.characters": "字符",
    "contact.page_badge": "联系我们", "contact.page_title": "开始一段", "contact.page_title_highlight": "对话",
    "contact.page_subtitle": "有项目想法？我们很乐意听取您的意见。",
    "contact.visit_us": "访问我们", "contact.business_hours": "工作时间", "contact.hours_value": "周日 - 周四: 9AM - 6PM", "contact.call_us": "致电我们",
  },
  ja: {
    "nav.home": "ホーム", "nav.about": "会社概要", "nav.services": "サービス", "nav.portfolio": "実績", "nav.demo": "デモ", "nav.blog": "ブログ", "nav.contact": "お問い合わせ",
    "cta.get_started": "始める",
    "footer.services": "サービス", "footer.company": "会社", "footer.contact": "お問い合わせ", "footer.rights": "全著作権所有。", "footer.made_with": "作成",
    "footer.enterprise_solutions": "エンタープライズソリューション", "footer.custom_development": "カスタム開発", "footer.security_finance": "セキュリティ＆金融", "footer.ai_integration": "AI統合",
    "footer.about_us": "会社概要", "footer.privacy": "プライバシーポリシー", "footer.terms": "利用規約",
    "hero.badge": "明日のイノベーションを今日に", "hero.title1": "ビジネスを", "hero.title2": "変革", "hero.title2_suffix": "する", "hero.title3": "最先端テクノロジーで",
    "hero.subtitle": "革新的なソフトウェアソリューション、AIシステム、専門ITコンサルティングを提供します。",
    "hero.cta_project": "プロジェクトを開始", "hero.cta_demo": "デモを見る",
    "hero.stat_projects": "納品プロジェクト", "hero.stat_satisfaction": "顧客満足度", "hero.stat_experts": "専門家チーム",
    "hero.scroll": "スクロール", "hero.tag_software": "ソフトウェア開発", "hero.tag_ai": "AIソリューション", "hero.tag_consulting": "ITコンサルティング", "hero.tag_cloud": "クラウドサービス",
    "services.badge": "サービス", "services.title": "私たちの", "services.title_highlight": "提供内容", "services.subtitle": "ビジネス成長を加速する包括的なテクノロジーソリューション。",
    "services.chat_now": "チャット", "services.view_all": "全サービスを見る",
    "services.enterprise": "エンタープライズソリューション", "services.enterprise_desc": "組織に合わせた総合ビジネス管理システム。",
    "services.custom": "カスタム開発", "services.custom_desc": "独自のビジネス要件に合わせたソフトウェアソリューション。",
    "services.security": "セキュリティ＆金融", "services.security_desc": "安全な金融システムとコンプライアンス対応ソリューション。",
    "services.ai": "AI統合", "services.ai_desc": "AIを活用してビジネスを自動化・最適化。",
    "contact.badge": "お問い合わせ", "contact.title": "一緒に", "contact.title_highlight": "素晴らしいものを",
    "contact.subtitle": "最先端技術でビジネスを変革する準備はできていますか？",
    "contact.email_us": "メール", "contact.whatsapp": "WhatsApp", "contact.location": "所在地",
    "contact.form_title": "メッセージを送る", "contact.form_subtitle": "24時間以内に返信します",
    "contact.name": "お名前", "contact.email": "メールアドレス", "contact.phone": "電話番号", "contact.subject": "件名",
    "contact.message": "メッセージ", "contact.message_placeholder": "プロジェクトについて教えてください...",
    "contact.send": "送信", "contact.sending": "送信中...",
    "contact.success_title": "送信完了！", "contact.success_desc": "早急にご連絡いたします。",
    "contact.error": "送信に失敗しました。再試行してください。", "contact.characters": "文字",
    "contact.page_badge": "お問い合わせ", "contact.page_title": "会話を", "contact.page_title_highlight": "始めましょう",
    "contact.page_subtitle": "プロジェクトをお持ちですか？ぜひお聞かせください。",
    "contact.visit_us": "訪問", "contact.business_hours": "営業時間", "contact.hours_value": "日〜木: 9時〜18時", "contact.call_us": "電話",
  },
  ko: {
    "nav.home": "홈", "nav.about": "소개", "nav.services": "서비스", "nav.portfolio": "포트폴리오", "nav.demo": "데모", "nav.blog": "블로그", "nav.contact": "문의",
    "cta.get_started": "시작하기",
    "footer.services": "서비스", "footer.company": "회사", "footer.contact": "문의", "footer.rights": "모든 권리 보유.", "footer.made_with": "제작",
    "footer.enterprise_solutions": "기업 솔루션", "footer.custom_development": "맞춤 개발", "footer.security_finance": "보안 및 금융", "footer.ai_integration": "AI 통합",
    "footer.about_us": "회사 소개", "footer.privacy": "개인정보 처리방침", "footer.terms": "이용약관",
    "hero.badge": "오늘의 혁신, 내일의 미래", "hero.title1": "비즈니스를", "hero.title2": "혁신", "hero.title2_suffix": "하세요", "hero.title3": "최첨단 기술로",
    "hero.subtitle": "혁신적인 소프트웨어 솔루션, AI 시스템, 전문 IT 컨설팅을 제공합니다.",
    "hero.cta_project": "프로젝트 시작", "hero.cta_demo": "데모 보기",
    "hero.stat_projects": "완료 프로젝트", "hero.stat_satisfaction": "고객 만족도", "hero.stat_experts": "전문가 팀",
    "hero.scroll": "스크롤", "hero.tag_software": "소프트웨어 개발", "hero.tag_ai": "AI 솔루션", "hero.tag_consulting": "IT 컨설팅", "hero.tag_cloud": "클라우드 서비스",
    "services.badge": "서비스", "services.title": "우리가", "services.title_highlight": "제공하는 것", "services.subtitle": "비즈니스 성장을 가속화하는 종합 기술 솔루션.",
    "services.chat_now": "채팅", "services.view_all": "모든 서비스 보기",
    "services.enterprise": "기업 솔루션", "services.enterprise_desc": "조직에 맞춘 종합 비즈니스 관리 시스템.",
    "services.custom": "맞춤 개발", "services.custom_desc": "고유한 비즈니스 요구에 맞는 소프트웨어 솔루션.",
    "services.security": "보안 및 금융", "services.security_desc": "안전한 금융 시스템과 규정 준수 솔루션.",
    "services.ai": "AI 통합", "services.ai_desc": "AI를 활용하여 비즈니스를 자동화하고 최적화.",
    "contact.badge": "문의하기", "contact.title": "함께 만들어요", "contact.title_highlight": "멋진 것을",
    "contact.subtitle": "최첨단 기술로 비즈니스를 혁신할 준비가 되셨나요?",
    "contact.email_us": "이메일", "contact.whatsapp": "WhatsApp", "contact.location": "위치",
    "contact.form_title": "메시지 보내기", "contact.form_subtitle": "24시간 내 답변",
    "contact.name": "이름", "contact.email": "이메일 주소", "contact.phone": "전화번호", "contact.subject": "제목",
    "contact.message": "메시지", "contact.message_placeholder": "프로젝트에 대해 알려주세요...",
    "contact.send": "보내기", "contact.sending": "보내는 중...",
    "contact.success_title": "전송 완료!", "contact.success_desc": "빠른 시일 내에 연락드리겠습니다.",
    "contact.error": "전송 실패. 다시 시도해주세요.", "contact.characters": "자",
    "contact.page_badge": "문의", "contact.page_title": "대화를", "contact.page_title_highlight": "시작합시다",
    "contact.page_subtitle": "프로젝트가 있으신가요? 연락 주세요.",
    "contact.visit_us": "방문", "contact.business_hours": "영업시간", "contact.hours_value": "일~목: 오전9시~오후6시", "contact.call_us": "전화",
  },
};

const languageNames: Record<Language, string> = {
  en: "English", bn: "বাংলা", ar: "العربية", hi: "हिन्दी", es: "Español", fr: "Français", de: "Deutsch", zh: "中文", ja: "日本語", ko: "한국어",
};

function detectBrowserLanguage(): Language {
  const stored = localStorage.getItem("app-language");
  if (stored && stored in translationsMap) return stored as Language;
  const browserLangs = navigator.languages || [navigator.language];
  for (const lang of browserLangs) {
    const code = lang.split("-")[0].toLowerCase() as Language;
    if (code in translationsMap) return code;
  }
  return "en";
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  languages: [],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(detectBrowserLanguage);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = useCallback((key: string): string => {
    return translationsMap[language]?.[key] || translationsMap.en[key] || key;
  }, [language]);

  const languages = Object.entries(languageNames).map(([code, name]) => ({
    code: code as Language,
    name,
    flag: languageFlags[code as Language],
  }));

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
